### ISSUE TITLE
多端口通訊會導致閒時平均流量上升

### ISSUE THREAD

**Issue by yatounoneko** [enfein/mieru#100]
測試在10個端口左右，閒時平均流量較低不會觸發國內小雞的某雲按需計費。（僅參考用途）

測試在60多個端口左右閒時流量會觸發計費。
![Screenshot_20231213_103749](https://github.com/enfein/mieru/assets/22129910/013b78b3-31ff-4c88-ac4b-b66a291011e8)
關閉客戶端後服務端主機即使開著mita也不再扣費
（已排除其他因素導致流量增加）

如果24小時長連客戶端，越多端口會造成流量增加的情況。

版本：2.2.0

**Comment by enfein** [comment]
如果所有端口都使用 TCP 协议，不论开多少个端口应该都不会出现这个问题。

如果使用 UDP 协议，UDP 每隔几秒钟会发送一个保活包，让会话不至于被清理掉。和所有其他数据包一样，保活包是会填充内容的，而且依据现在的算法，越短的包可能会填充越长的内容，所以最后的结果是每个保活包都会跑掉几百字节，会话挂机时间长了会产生一些流量。

关闭客户端之后，会话都断了，也就不会继续产生流量了。

**Comment by yatounoneko** [comment]
> 如果所有端口都使用 TCP 协议，不论开多少个端口应该都不会出现这个问题。
> 
> 如果使用 UDP 协议，UDP 每隔几秒钟会发送一个保活包，让会话不至于被清理掉。和所有其他数据包一样，保活包是会填充内容的，而且依据现在的算法，越短的包可能会填充越长的内容，所以最后的结果是每个保活包都会跑掉几百字节，会话挂机时间长了会产生一些流量。
> 
> 关闭客户端之后，会话都断了，也就不会继续产生流量了。

原來是udp的機制，看來設置多端口靠tcp存活，udp用幾個端口就好了，謝謝你👍
