### ISSUE TITLE
UDP listening to one port 

### ISSUE THREAD

**Issue by ellahmezar** [enfein/mieru#101]
Hi @enfein  ,
Hope you're doing great .
I put 4443 udp port for mita , but it seems mita listens to several udp ports in server .
Is there any way that mita only listens to one specific udp port ? ( 4443 )
Sincerely Yours 🌱

**Comment by enfein** [comment]
> but it seems mita listens to several udp ports in server

This is not true.

Start from example https://github.com/enfein/mieru/blob/main/configs/examples/server_config.json

If you only want to listen to UDP 4443, change

```
    "portBindings": [
        {
            "portRange": "2012-2022",
            "protocol": "TCP"
        },
        {
            "port": 2027,
            "protocol": "TCP"
        }
    ],
```

to

```
    "portBindings": [
        {
            "port": 4443,
            "protocol": "UDP"
        }
    ],
```

then apply, stop, start mita to make new settings effective. Don't forget to change your mieru client settings as well to match server configuration.

**Comment by ellahmezar** [comment]
I exactly import this on server 👇🏻
    "portBindings": [
        {
            "port": 4443,
            "protocol": "UDP"
        }
    ],
But it uses other udp port ( more than 10 udp ports ) along with 4443

**Comment by enfein** [comment]
It shouldn't be.

Can you paste the output of `mita describe config` portBindings section to here? How do you know it is using other UDP ports?

**Comment by ellahmezar** [comment]
@enfein 
Sure , Here is mita describe config 👇🏻

![Screenshot_20231214_091839_Termius](https://github.com/enfein/mieru/assets/129280842/e93d930f-2c4f-40dc-9dbd-0e3a9e65700b)

By entering netstat - tulpn command in vps , it will shown the listening ports 👇🏻
( You can see many ports are occupied ) 

![Screenshot_20231214_092120_Termius](https://github.com/enfein/mieru/assets/129280842/7b9d4280-2b60-42f0-abc7-422d5a3c9d23)

**Comment by enfein** [comment]
I see. Most likely your mieru client is running socks5 UDP associate. Check this line from the server log:

```
INFO [metrics - socks5 UDP associate] InBytes=1767082 InPkts=7785 OutBytes=34915053 OutPkts=30381
```

If those numbers keep increasing then that is the cause, and this is completely normal.

**Comment by ellahmezar** [comment]
@enfein 
So if this is normal , why do mieru and other udp platforms like TUIC & Hysteria 2 use other udp ports ?
[ I mean they don't listen to only one specific port ]

**Comment by enfein** [comment]
It is possible to use a single UDP port at the server side to implement socks5 UDP associate, to my opinion that will not be able to support full cone NAT.
