### ISSUE TITLE
mieru blocked

### ISSUE THREAD

**Issue by mortada-jafar** [enfein/mieru#102]
I have a server with the IP address x.x.x.x. Although it has a 'dirty' IP, it is not blocked by the Great Firewall (GFW). I have verified this by checking the IP with  OpenConnect and Reality and SSH, and it works perfectly with a clean Server Name Indication (SNI).
**again with clean SNI**

However, when testing with Mieru, the connection is not successful. I have conducted tests using both TCP and UDP individually, as well as TCP and UDP together, but there is no positive result.

mieru version: 2.2.0

Server Log:

![image_2023-12-15_01-30-52](https://github.com/enfein/mieru/assets/11082696/4d1a71cc-6bee-4055-8100-fbbcfb40ad44)

Client Log:

![image_2023-12-15_01-31-06](https://github.com/enfein/mieru/assets/11082696/2c21e0de-8a15-41fb-94c5-4feee17ba1f4)

**Comment by enfein** [comment]
I don't know what a dirty IP and clean SNI mean. mieru doesn't use TLS so SNI doesn't matter.

Also, it looks like the logs are not collected at the same time. Can I summarize the symptom like this? **Client gets few packets from server after it sends out requests to establish connection.**

Can you also stop the client and monitor the server log? Check if any metrics number is increasing while you are not using it.

**Comment by mortada-jafar** [comment]
i think the problem in my side  I will check it again  

Thanks
