### ISSUE TITLE
Get users traffic usage from CLI

### ISSUE THREAD

**Issue by mortada-jafar** [enfein/mieru#103]
how can I get users' traffic usage?
Is there any API interface or CLI command to extract this data?
Is there any API interface or CLI command to add/edit/delete users without restarting and interrupting the connections?

**Comment by enfein** [comment]
> Is there any API interface or CLI command to extract this data?

Nothing right now. It is only visible from server log. But we will working on exporting the metrics.

> Is there any API interface or CLI command to add/edit/delete users without restarting and interrupting the connections?

This work will be done in issue #93.
