### ISSUE TITLE
Using Domain Instead of IPAddress for Server Nodes with Shared Users

### ISSUE THREAD

**Issue by mortada-jafar** [enfein/mieru#104]
Is it possible to utilize the domain in place of the `ipAddress`? In a scenario where server nodes are consolidated under a single domain, and users are distributed across all nodes, how can I configure this domain in the client settings?

What is the purpose or objective of the `domainName` property?

**Comment by enfein** [comment]
Domain name is supported in the client configuration. For example,

```
            "servers": [
                {
                    "domainName": "your.vps.domain.name",
                    "portBindings": [
                        {
                            "portRange": "2012-2022",
                            "protocol": "TCP"
                        },
                        {
                            "port": 2027,
                            "protocol": "TCP"
                        }
                    ]
                }
            ],
```

As a caveat, this domain name must be able to resolved by the client locally.
