### ISSUE TITLE
Windows Tray App

### ISSUE THREAD

**Issue by cr4zyfish** [enfein/mieru#108]
I created a windows tray app here:
https://github.com/cr4zyfish/TrayApp

So you dont need to keep a cmd window open.

**Comment by enfein** [comment]
@cr4zyfish Thank you! I will work with you on the user document.

**Comment by tgnglink** [comment]
win11的cmd和powershell可以直接设置最小化到托盘，可以不用第三方软件的，cmd或powershell窗口上方标签条+号右边有个小箭头，点开， 选“设置”，然后“外观”，在下方找到 “最小化时在通知区域隐藏终端” 打开，保存就ok，最小化的时候就自动到托盘了，cmd和powershell共用一个设置，不用分别设置。win10不知道有没有这功能
