### ISSUE TITLE
甲骨文arm安装2.2.0后无效

### ISSUE THREAD

**Issue by jjyou-github** [enfein/mieru#110]
甲骨文arm机器ubuntu 22 aarch系统，wget arm 2.2.0的deb后，dpkg -i安装。提示成功，实际没有。
![arm_mita安装无效](https://github.com/enfein/mieru/assets/63731955/e040ac56-8d78-4a13-912f-6e03e631c6a2)

**Comment by jjyou-github** [comment]
怀疑是aarch 与arm架构不同，先关闭。回头用正常的系统再试试。

**Comment by enfein** [comment]
请安装 mita_2.2.0_arm64.deb 而不是 mieru_2.2.0_arm64.deb

aarch64 等于 arm64
