### ISSUE TITLE
Mieru's MTU conflicts with NekoBox' MTU 

### ISSUE THREAD

**Issue by ellahmezar** [enfein/mieru#111]
Hi @enfein ,
Hope you're doing great .

First I set 1500 for main MTU in Nekobox app ( I set 1472 for MTU in server mita's config file ) , then I enter 1472 in Nekobox's Mieru profile config and applied that  ,but when I returned to setting section in Nekobox , the main MTU that I set 1500 , was changed automatically to 1400 👇🏻👇🏻👇🏻
![Screenshot_20240111_203740_NekoBox](https://github.com/enfein/mieru/assets/129280842/200c8f47-ade0-4ded-be7d-2cc2d906f942)
![Screenshot_20240111_203804_NekoBox](https://github.com/enfein/mieru/assets/129280842/c8a5f6d3-288e-4dc5-8735-8e075c9b16fd)
![Screenshot_20240111_203929_NekoBox](https://github.com/enfein/mieru/assets/129280842/180e8eb9-be9f-4cfe-9c03-de37e8c388b7)

Please solve this bug 🌱
Best Regards

**Comment by enfein** [comment]
This is bug. The expected behavior is either the app MTU is set to be the same value as mieru MTU, or app MTU is independent from the mieru MTU.

**Comment by ellahmezar** [comment]
@enfein ,
Here in your Mieru guidance for installing [ https://github.com/enfein/mieru/blob/main/docs/client-install.md ] , you put MTU 1400 for default clients , I think you should fix this in Nekobox .👇🏻

{
    "profiles": [
        {
            "profileName": "default",
            "user": {
                "name": "ducaiguozei",
                "password": "xijinping"
            },
            "servers": [
                {
                    "ipAddress": "12.34.56.78",
                    "domainName": "",
                    "portBindings": [
                        {
                            "portRange": "2012-2022",
                            "protocol": "TCP"
                        },
                        {
                            "port": 2027,
                            "protocol": "TCP"
                        }
                    ]
                }
            ],
            "mtu": 1400,
            "multiplexing": {
                "level": "MULTIPLEXING_HIGH"
            }
        }
    ],
    "activeProfile": "default",
    "rpcPort": 8964,
    "socks5Port": 1080,
    "loggingLevel": "INFO",
    "socks5ListenLAN": false,
    "httpProxyPort": 8080,
    "httpProxyListenLAN": false
}

**Comment by ellahmezar** [comment]
I also omited MTU both in server side and Nekobox's config profile ,but again the main Nekobox's MTU changes to 1400

**Comment by enfein** [comment]
@ellahmezar Can you try the APK from https://github.com/enfein/NekoBoxForAndroid/actions/runs/7550857326 and check if the bug is fixed?

**Comment by ellahmezar** [comment]
Hi @enfein ,
It seems that this bug is fixed 🌱🫰🏻
Many thanks .
Please work on ZERO upload speed , there is no upload in both tcp & udp .

**Comment by enfein** [comment]
Published a new release https://github.com/enfein/NekoBoxForAndroid/releases/tag/1.3.0-20240123 which includes the fix.
