### ISSUE TITLE
Speedtest: connection dropping and 0 upload speed

### ISSUE THREAD

**Issue by ellahmezar** [enfein/mieru#112]
Hi @enfein 
Hope you're doing great .
These are speedtest's results from Mieru from 2 different server .
![Screenshot_20240111_211409_Speedtest](https://github.com/enfein/mieru/assets/129280842/287f9b96-890d-41ed-aeff-28b0b08a36fe)
![Screenshot_20240111_211314_Speedtest](https://github.com/enfein/mieru/assets/129280842/1a70d59a-5e06-48f5-8822-414e3c13f197)
Two important problems shown in results :

1/Connection dropping
2/Zero upload speed .
Please fix these two important problem in Mieru . Mieru can be the best plugin even better than Hysteria 2 and Tuic .
Best regards my brother 🌱🌹

**Comment by enfein** [comment]
Does this happen to UDP, TCP, or both?

**Comment by ellahmezar** [comment]
It happens in UDP .
UDP has better situation than TCP in my area .
I didn't test TCP .

**Comment by ellahmezar** [comment]
Here is the TCP conncection , same port and setting .
I can't upload anything to any website .
Also online website watching like youtube has disruption because of connection dropping .
It's not speedtest's problem , totally the problems refer to mieru .
![Screenshot_20240112_114157_Speedtest](https://github.com/enfein/mieru/assets/129280842/04cbc781-7f5b-45a0-b646-e5ac0da3a1dc)

**Comment by enfein** [comment]
In my case, when UDP is used, the upload speed is 0 and test returns error, when TCP is used, the upload speed is not 0. I haven't seen disruption, maybe because the phone is for testing and not daily use.

**Comment by ellahmezar** [comment]
On my side both TCP & UDP upload speed is 0 , but there is no problem for upload on the other plugins like Hysteria .

**Comment by enfein** [comment]
I am able to run speedtest multiple times without a problem with v2.3.0 and TCP protocol. UDP is still problematic due to server high memory usage. Will try to fix that later.

**Comment by ellahmezar** [comment]
@enfein 
In my area , TCP Upload speed is 0 😓 Just like UDP

**Comment by enfein** [comment]
We found memory pressure while executing the speed test, and resolved that issue in 2.4.0, 2.5.0 and 2.6.0 releases. However, mieru was still unable to handle the special speed test workload due to some reasons. Besides speed test, everything else is working as expected. We believe it is not worth to further debugging on this.
