### ISSUE TITLE
UDP Time-out in Mieru

### ISSUE THREAD

**Issue by ellahmezar** [enfein/mieru#113]
Hi @enfein ,
What is the default time-out amount for UDP in Mieru ?
[ Idle udp time-out in other plugins like Hysteria is 60 seconds ]

**Comment by enfein** [comment]
It is 60 seconds.

https://github.com/enfein/mieru/blob/f5a53d7f9b736d33a4e642233ce6b9ca82e92fec/pkg/protocolv2/underlay_udp.go#L41
