### ISSUE TITLE
Add Mieru to sing-box core

### ISSUE THREAD

**Issue by ellahmezar** [enfein/mieru#114]
Hi @enfein ,
Hope you're doing well .
You can talk ,and cooperate with @sagernet for adding Mieru in sing-box core both in inbound and outbound mode . [ People can tuunel from other plugins to Mieru ,or from Mieru to other plugins ]
The other advantage is that people can conncet from Nekobox to Mieru **directly** (Without any plugins just like other connection ways such as TUIC , Hysteria ,and . . . )
It reduces ping both in Mieru conncetion itself ,and the ping shown in Nekobox app .
Hope doing this faster . 
Best Regards 🌹🌱

**Comment by enfein** [comment]
We will try this after the core features and protocols are stable.
