### ISSUE TITLE
 dial unix /var/run/mita.sock: connect: no such file or directory"

### ISSUE THREAD

**Issue by cr4zyfish** [enfein/mieru#117]
I uninstalled mita server 2.2 and installed 2.3 now when i run mita stop or mita start or mita apply config i get this error:

![error](https://github.com/enfein/mieru/assets/90797624/f9d920ed-b856-40e0-90f2-5d547b0c6000)

mita server version is 2.3.0 and client version is 2.2.0 and it is working. but trying to apply new config at server gives that error.

**Comment by enfein** [comment]
Can you check if mita service is running: `systemctl status mita`?

If not running, do `sudo systemctl start mita`.

Then all the CLI should work.
