### ISSUE TITLE
rpcPort and upstream proxy

### ISSUE THREAD

**Issue by cr4zyfish** [enfein/mieru#118]
Hi i have 2 questions
1. what is rpcPort in client config? can i remove it?
2. how to set upstream proxy in mieru client? so mieru first connects to proxy 127.0.0.1:1080 when -> mita server?

**Comment by enfein** [comment]
1. `rpcPort` is listening to the CLI commands you type in the terminal. Yes it is OK to remove, but operation will be difficult and you can't use those CLI commands anymore. For example, you can remove the rpcPort and use a systemd service to start and stop mieru.
2. There is no configuration in mieru to support upstream proxy. You should be able to do either nested proxy, where mieru is in the middle, or proxy chaining.
