### ISSUE TITLE
TUN list

### ISSUE THREAD

**Issue by Pantyhose-X** [enfein/mieru#119]
[Wintun](https://github.com/nulldotblack/wintun)
[ligolo-ng](https://github.com/nicocha30/ligolo-ng)
[wireguard TUN](https://github.com/WireGuard/wireguard-go/tree/master/tun)
[Universal TUN/TAP driver](https://vtun.info/)
[tun2socks](https://github.com/xjasonlyu/tun2socks)
[tun2proxy](https://github.com/blechschmidt/tun2proxy)

**Comment by enfein** [comment]
No plan to have builtin TUN support in mieru. Welcome to use any of those in the list. Personally I use clash. Now clash is dead and I will move to something else.

**Comment by qfomg** [comment]
@enfein  大佬，软件能支持电脑32位系统吗？

**Comment by enfein** [comment]
@qfomg 你需要哪个操作系统的 32 位客户端？另外操作系统是什么版本？我们应该不会长期维护上古的系统。

**Comment by qfomg** [comment]
@enfein win10系统

**Comment by enfein** [comment]
@qfomg 好的，下个版本安排上

**Comment by qfomg** [comment]
> @qfomg 好的，下个版本安排上

谢谢大佬，大佬辛苦了

**Comment by qfomg** [comment]
@enfein  用的最新的32位版本。推荐的TCP配置信息。打开网站，会有20%概率打不开（测试10次，关闭软件重新打开），有时候刷新页面1次可打开，有时候刷新2～4次可打开。

打不开时，网页显示如下：
![屏幕截图 2024-03-07 223911130](https://github.com/enfein/mieru/assets/159746504/64af1554-ca91-4e88-9b68-717a7653be1b)

刷新网页N次后，网页成功打开：
![屏幕截图 2024-03-07 223922259](https://github.com/enfein/mieru/assets/159746504/7b6865da-a2ff-4696-83e6-684555b3a236)

不知道是最新版本都有这个问题，还是只是32位的windows版本，反馈一下。

**Comment by qfomg** [comment]
补充：除了首次打开网页会有这个问题以外。在使用的过程中也会有一定的概率遇到打不开其它网页的情况，一般需要刷新网页来解决。

**Comment by enfein** [comment]
@qfomg 

出现故障后，能否在本地和服务器上分别运行 `mieru get metrics` 和 `mita get metrics` 指令，然后把结果贴过来？这有助于初步定位问题。

**Comment by Alvin9999** [comment]
@enfein  本地结果：
{
    "cipher - client": {
        "DirectDecrypt": 879,
        "FailedDirectDecrypt": 0
    },
    "connections": {
        "ActiveOpens": 57,
        "CurrEstablished": 21,
        "MaxConn": 27,
        "PassiveOpens": 0
    },
    "HTTP proxy": {
        "ConnErrors": 0,
        "Requests": 0,
        "SchemeErrors": 0
    },
    "replay": {
        "KnownSession": 0,
        "NewSession": 0
    },
    "socks5": {
        "ConnectionRefusedErrors": 0,
        "DNSResolveErrors": 0,
        "HandshakeErrors": 24,
        "HostUnreachableErrors": 0,
        "NetworkUnreachableErrors": 0,
        "UDPAssociateErrors": 0,
        "UnsupportedCommandErrors": 0
    },
    "socks5 UDP associate": {
        "InBytes": 0,
        "InPkts": 0,
        "OutBytes": 0,
        "OutPkts": 0
    },
    "traffic": {
        "InBytes": 1244261,
        "OutBytes": 177390,
        "OutPaddingBytes": 39925
    },
    "underlay": {
        "ActiveOpens": 22,
        "CurrEstablished": 8,
        "MaxConn": 8,
        "PassiveOpens": 0,
        "UnderlayMalformedUDP": 0,
        "UnsolicitedUDP": 0
    }
}

服务器结果：
{
    "cipher - server": {
        "DirectDecrypt": 44891,
        "FailedDirectDecrypt": 0,
        "FailedIterateDecrypt": 85,
        "IterateDecrypt": 888
    },
    "connections": {
        "ActiveOpens": 0,
        "CurrEstablished": 23,
        "MaxConn": 36,
        "PassiveOpens": 3646
    },
    "replay": {
        "KnownSession": 0,
        "NewSession": 0
    },
    "socks5": {
        "ConnectionRefusedErrors": 14,
        "DNSResolveErrors": 4,
        "HandshakeErrors": 25,
        "HostUnreachableErrors": 0,
        "NetworkUnreachableErrors": 0,
        "UDPAssociateErrors": 0,
        "UnsupportedCommandErrors": 0
    },
    "socks5 UDP associate": {
        "InBytes": 0,
        "InPkts": 0,
        "OutBytes": 0,
        "OutPkts": 0
    },
    "traffic": {
        "InBytes": 13256242,
        "OutBytes": 361291200,
        "OutPaddingBytes": 7833902
    },
    "underlay": {
        "ActiveOpens": 0,
        "CurrEstablished": 10,
        "MaxConn": 19,
        "PassiveOpens": 1019,
        "UnderlayMalformedUDP": 0,
        "UnsolicitedUDP": 0
    },
    "user - 2f19fbe1": {
        "ReadBytes": 631646,
        "WriteBytes": 9278851
    },
    "user - dongtaiwang.com": {
        "ReadBytes": 7563877,
        "WriteBytes": 340462642
    }
}

**Comment by enfein** [comment]
@Alvin9999 

服务器这边

```json
"socks5": {
"ConnectionRefusedErrors": 14,
"DNSResolveErrors": 4,
"HandshakeErrors": 25,
"HostUnreachableErrors": 0,
"NetworkUnreachableErrors": 0,
"UDPAssociateErrors": 0,
"UnsupportedCommandErrors": 0
}
```

`ConnectionRefusedErrors` 和 `DNSResolveErrors` 是这台服务器无法访问的网站，这个无能为力。

`HandshakeErrors` 表示对方提供的请求有问题。考虑到请求的数量很多

```json
"connections": {
"ActiveOpens": 0,
"CurrEstablished": 23,
"MaxConn": 36,
"PassiveOpens": 3646
}
```

看上去还可以。

客户端这边

```json
"connections": {
"ActiveOpens": 57,
"CurrEstablished": 21,
"MaxConn": 27,
"PassiveOpens": 0
},
"socks5": {
"ConnectionRefusedErrors": 0,
"DNSResolveErrors": 0,
"HandshakeErrors": 24,
"HostUnreachableErrors": 0,
"NetworkUnreachableErrors": 0,
"UDPAssociateErrors": 0,
"UnsupportedCommandErrors": 0
}
```

57 次连接有 24 个错误，这个比例太高了。看上去在你所在的地区，TCP 有一定概率会被针对。

一种缓解的办法是，在客户端设置中设置 `MULTIPLEXING_HIGH`，这样会以更大的概率重复使用以前的 TCP 连接，而不是创建新连接，例如

```json
{
    "profiles": [
        {
            "profileName": "default",
            "user": {
                "name": "baozi",
                "password": "manlianpenfen"
            },
            "servers": [
                {
                    "ipAddress": "12.34.56.78",
                    "portBindings": [
                        {
                            "portRange": "8964-8965",
                            "protocol": "TCP"
                        },
                        {
                            "port": 9648,
                            "protocol": "TCP"
                        },
                        {
                            "port": 6489,
                            "protocol": "TCP"
                        },
                        {
                            "port": 4896,
                            "protocol": "TCP"
                        }
                    ]
                }
            ],
            "multiplexing": {
                "level": "MULTIPLEXING_HIGH"
            }
        }
    ]
}
```

另外也请试一下 UDP 协议。伊朗人的说法是在那里 TCP 完全无法使用，但是 UDP 没有问题。

**Comment by cr4zyfish** [comment]
Download v2rayN :
https://github.com/2dust/v2rayN/releases/download/6.45/v2rayN-With-Core.zip

Add mieru as a socks proxy:
![image](https://github.com/enfein/mieru/assets/90797624/42cb6316-e7e2-4f8a-9cd9-f43b1f958fa1)
Click on Enable Tun:
![image](https://github.com/enfein/mieru/assets/90797624/57c7e95a-9aac-4c73-a9f5-42a2beffe874)

It works!

**Comment by notcreepy** [comment]
I have never seen a program with tun mode that works without problem. tun mode is always very slow. 
with mieru [tun2socks](https://github.com/xjasonlyu/tun2socks) works at least the first time.
