### ISSUE TITLE
Instructions for full uninstalling

### ISSUE THREAD

**Issue by ellahmezar** [enfein/mieru#121]
Hi @enfein .
Hope you're doing great !
I wanna the instructions for uninstalling & removing all files related to mieru & mita in Ubuntu server .
Best Regards!

**Comment by enfein** [comment]
## mieru

```
sudo dpkg -P mieru
rm -rf $HOME/.cache/mieru
rm -rf $HOME/.config/mieru
```

## mita

```
sudo dpkg -P mita
sudo rm -rf /etc/mita
sudo userdel mita
```

**Comment by ellahmezar** [comment]
Many thanks ✨️

**Comment by ellahmezar** [comment]
I entered these commands , but when you want to install mita again , it says that files still exists .

sudo dpkg -P mita
sudo rm -rf /etc/mita
sudo userdel mita

**Comment by enfein** [comment]
> it says that files still exists

Can you show an error message?

**Comment by ellahmezar** [comment]
@enfein
It's not an error .
When I entered all the above commands , It must remove ALL file and folders related to Mita .
After entering all above commands for uninstalling , when you want to reinstall Mita again , after "sudo dpkg -i mita " command , it shows a message that files ALREADY INSTALLED and it just overriding the files .
[ It should be like the first time that I installed Mita ,but it's not ]

**Comment by enfein** [comment]
I see. Let me check deb and rpm script.

**Comment by enfein** [comment]
@ellahmezar Can you download https://github.com/enfein/mieru/blob/main/tools/uninstall_mita.py and execute that in your server? That will remove every file related to mita proxy server.

**Comment by ellahmezar** [comment]
@enfein 
I can download it on my server , but I don't know how to execute it

**Comment by enfein** [comment]
After you download the file, run

```shell
sudo python3 uninstall_mita.py
```

**Comment by ellahmezar** [comment]
@enfein 
Are you sure that this script will remove ALL files and folder related to mita in ubuntu vps ?
https://github.com/enfein/mieru/blob/main/tools/uninstall_mita.py

**Comment by enfein** [comment]
I think so. You should no longer see a file already installed.

I also put the following content in the script. Please read carefully.

```text
WARNING: this program is NOT safe against forensic collection, because
mita runtime information may be stored in system journal log.
```
