### ISSUE TITLE
 Reduce ping in Mita

### ISSUE THREAD

**Issue by ellahmezar** [enfein/mieru#123]
Hi @enfein 
Is there any way to reduce ping ,or rate of handshake in Mita ?
Many thanks 🌹🪻

**Comment by enfein** [comment]
Number of handshake equals to number of connections established. We can't control.

If you are using UDP, ACK are sent. It is possible to adjust ACK behavior by changing the code.

Is there a particular issue that you want to solve?

**Comment by ellahmezar** [comment]
@enfein 
It would be fantastic for gamers if the ping of connection is reduced .
I think you can do something for reducing the ping

**Comment by enfein** [comment]
I see. You are talking about delay.

There is nothing we can do in TCP. In UDP, the only thing I can do is reducing the event loop interval. That can save max 20ms round trip by burning more CPU. Maybe it is OK to enable this for non Android device.

**Comment by ellahmezar** [comment]
@enfein 
I am using UDP . If it is effective , please do whatever you can for reducing delay and increasing the speed 🫰🏻
I am using mita in android phone , I think it also works on android .
Do whatever you can !

**Comment by enfein** [comment]
I will not make change in Android to avoid draining the battery too fast. You will still benefit from the server side though.

**Comment by ellahmezar** [comment]
@enfein 
Yes , I mean do anything you can in server side for reducing delay in UDP .
I makes Mita great for gaming and video call !
