### ISSUE TITLE
Question about updating mita

### ISSUE THREAD

**Issue by cr4zyfish** [enfein/mieru#126]
I updated mita server just by:
curl -LSO https://github.com/enfein/mieru/releases/download/v2.7.0/mita_2.7.0_amd64.deb
sudo dpkg -i mita_2.7.0_amd64.deb

Is this correct or i need to uninstall old version first?

**Comment by enfein** [comment]
This is correct. You don't need to uninstall the old version by yourself. `dpkg` will uninstall the old one for you and install the new one. You can verify the version with `mita version` command.
