### ISSUE TITLE
Android app

### ISSUE THREAD

**Issue by masterpacket** [enfein/mieru#129]
I have some questions.
I have mieru version 3 client and server. protocol TCP. also tried udp.
with nekobox only telegram works and other apps do not work. does any body else have this problem?
twitter app also works but only text is loading and images are not loading. what could be the reason? vless works fine but mieru is like this.
Is anyway to send message to user after traffic limit reached? like: "your daily traffic is reached"

**Comment by enfein** [comment]
Is the ping working for you in NekoBox? There are a lot of settings in NekoBox for per app proxy, GeoIP filter, etc. They are out of mieru's control.

In the NekoBox there is no easy way to know if the traffic limit is reached. In desktop you can get this information by checking mieru client log files.

**Comment by masterpacket** [comment]
TCPing and URL test is working.
NekoBox Settings is default. No per app proxy .
On desktop it is working without problem.
on android some apps are not working at all. some apps work sometimes. Some apps like Telegram always works and its fast.
