### ISSUE TITLE
If I read the udp code, where should I begin?

### ISSUE THREAD

**Issue by qeatzy** [enfein/mieru#13]
I want to read the code to learn how to properly support udp mode.

I mainly interested in pure golang version, with
- no configuration, all comes in command arguments (support ENV as default). Even wrote argparser for that.
- only a handful files and minimize external dependency.
to 
- fast prototyping
Might implement config level if all lower level are more full grown.

Since I'm unfamiliar with udp & kcp, where shall I start? Which file or directory should I dive into?

**Comment by enfein** [comment]
Let's use a top down approach.

In `pkg/udpsession/session.go`, `DialWithOptions` is where the client creates the UDP connection. `ListenWithOptions` is where the server listens to incoming UDP packets. In both cases, `UDPSession` implements `net.Conn` interface and manages the UDP connection.

The underlying I/O uses KCP, which you can find in `pkg/kcp/kcp.go`. KCP has mainly four functions. `Send` sends app data to KCP, `Recv` delivers KCP buffered data to app, `Input` fetches transport data and buffer it in KCP, `Output` flushes KCP data to transport.

**Comment by qeatzy** [comment]
我只能说有些人的小号用的真漂亮，1+2，一点也不露痕迹，比ssr issue 38里高明多了，2022-04-29是关键节点。

**Comment by qeatzy** [comment]
就一条commit，还是merge别人的。。
