### ISSUE TITLE
Reply Attack?

### ISSUE THREAD

**Issue by cr4zyfish** [enfein/mieru#132]
What do these metrics mean? I had some disruptions In the last week. with ssh traffic completely working fine, mieru was very slow and sometimes not connected at all. country=Iran  version=3.0.0

![aaaaaaa](https://github.com/enfein/mieru/assets/90797624/076102db-c276-4cac-8a62-09039d6f7dd2)
![bbb](https://github.com/enfein/mieru/assets/90797624/3e505749-0a2d-4ca2-a5c5-110b8b519ea9)

I installed version v3.0.1 and the statistics are now reset and these metrics are currently zero.

**Comment by enfein** [comment]
A replay attack means that the same network packet is sent to the server or client multiple times.

It doesn't mean GFW is probing your server. A simple port scan, which is very common, can increase the number.

We can improve the metrics to show more information, e.g. if the packet can be decrypted.

**Comment by enfein** [comment]
Also issue #133 will help.
