### ISSUE TITLE
Feature Request: port forwarding

### ISSUE THREAD

**Issue by Dexterhex** [enfein/mieru#135]
add port forwarding feature to mieru.
For example mieru connects to mita server in port 8080
any packets sent to local port 7070 (user pc) is sent to server local port 1194 via mieru tunnel witch established in port 8080.
so isp sees data is sent to mita 8080 only.

server to server port forwarding:
server 1 (with mieru) connects to server 2 (has mita)
we send packets to port 7070 in server 1 and traffic is sent through port 8080 to server 2 an received in port 1194.

Usage: use other vpn protocols that are currently blocked in GFW like openvpn or wireguard.

**Comment by enfein** [comment]
I recommend you read this first: https://github.com/enfein/mieru/blob/main/docs/server-install.md#configuring-outbound-proxy

There are two ways to work with other proxies: proxy chaining and nested proxy. Both are supported. Let me know which one fit better and I can provided further instructions.

**Comment by notcreepy** [comment]
{
                "name": "cloudflare",
                "protocol": "SOCKS5_PROXY_PROTOCOL",
                "host": "127.0.0.1",
                "port": 4000
            }
            
            How to enter password of outbound proxy?

**Comment by enfein** [comment]
@notcreepy Password of outbound proxy is not supported at the moment. You can add a feature request. socks5 password is clear text and add no additional security.
