### ISSUE TITLE
Problem in windows 11

### ISSUE THREAD

**Issue by dopraxerz** [enfein/mieru#136]
I have a problem with mieru v 3 in windows 11. It behaves like it can not read the correct system time. when i downgrade to v 2.7.0 it works fine. 
with version 3.0.1 In windows 10 I changed system time to a wrong time then I looked in wireshark, small packets are sent and received from server. the behaviour with mieru v 3 in windows 11 is the same. is anything related to time changed in mieru v3?
Also there is a question. when system time is wrong, how is even packets exchanged between user and server? 

update: I see the problem in windows 10 too sometimes. I downgraded to v 2.7 for now.

**Comment by enfein** [comment]
Do you mean the mieru v2 doesn't have the same behavior?

Time setting impact new connections, not existing connections, and TCP handshake will always happen.

If the time difference is more than 10 minutes, and then you start mieru client, in the metrics you won't see `DirectDecrypt` packets.

**Comment by dopraxerz** [comment]
Mieru v 2.7 works completly fine. only when system time is wrong, it gives "Unable to connect" Error in browser. But version 3 gives this error without reason.
is it related to issue you created? https://github.com/enfein/mieru/issues/138
I think there is a problem with mieru version 3

**Comment by enfein** [comment]
If the system time is correct and you still see Unable to connect, then it is possible you hit issue #138.
