### ISSUE TITLE
mieru client is not running: connection refused

### ISSUE THREAD

**Issue by theonewhopassed** [enfein/mieru#137]
hi
i have wiered issues with mieru
for example when the mieru client is started I type mieru get connections i get an error like this

get connections failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded

or sometimes when I type mieru start i get an error like this

mieru client is not running: ClientLifecycleService.GetStatus() failed: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp [::1]:8964: connect: connection refused"

what is the workaround for these kinds of errors?

**Comment by enfein** [comment]
Are you using Windows?

If you got error when running "mieru start", it means the process is not reachable after 10 seconds. It is likely the anti-virus program is doing something.

**Comment by enfein** [comment]
@theonewhopassed Most likely the port number is already occupied. You can check the mieru log to confirm. We are working on improving the error messages.

**Comment by theonewhopassed** [comment]
no Im using linux and there is no other proccess using that port rather than mieru itself and the issue happens when I stop and start mieru multiple times

**Comment by enfein** [comment]
When the problem happens, can you check the latest mieru log file from `$HOME/.cache/mieru` and see if there is any FATAL log?

**Comment by Aquarii** [comment]
> Most likely the port number is already occupied. You can check the mieru log to confirm. We are working on improving the error messages.

Hi 
I'm on windows and have the same problem. the port is open. and the log level is FATAL:
```
2024-06-04T18:30:00+03:30 FATAL listen on socks5 address tcp "127.0.0.1:1080" failed: listen tcp 127.0.0.1:1080: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
```

btw, my error msg is a bit different:
```mieru client is not running: ClientLifecycleService.GetStatus() failed: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp [::1]:8964: connectex: No connection could be made because the target machine actively refused it."```

**Comment by theonewhopassed** [comment]
FATAL run HTTP proxy server failed: listen tcp 127.0.0.1:8080: bind: address already in use 
but there is no service other than mieru itself 
this issue happens if i stop and restart mieru multiple times

the version this issue is happening is 3.0.1 I didn't test 3.1.0 if the issue is resolved

**Comment by enfein** [comment]
There are a few places where the `SO_REUSEADDR` and `SO_REUSEPORT` are not set, which could lead to this problem.

This only works for Linux.
