### ISSUE TITLE
Version 3.1.0 detected a virus

### ISSUE THREAD

**Issue by wzmnge** [enfein/mieru#139]
Version 3.1.0 detected a virus .The systerm of my computer is win11.
Thank you sir

**Comment by enfein** [comment]
I have uploaded the two zip files to VirusTotal.

The checksum of the two zip files are

```
$ cat mieru_3.1.0_windows_amd64.zip.sha256.txt 
3877ac56e37317ab92f98d9a08b2a2247edf6f5b02d745a25c106b725a7286b6  mieru_3.1.0_windows_amd64.zip

$ cat mieru_3.1.0_windows_x86.zip.sha256.txt 
bb5234d00b50374146fb2049f685cc3b8106759c02c4c6faa265a3d2085f9c13  mieru_3.1.0_windows_x86.zip
```

You can find the VirusTotal report from the following two URLs:

```
https://www.virustotal.com/gui/file/3877ac56e37317ab92f98d9a08b2a2247edf6f5b02d745a25c106b725a7286b6

https://www.virustotal.com/gui/file/bb5234d00b50374146fb2049f685cc3b8106759c02c4c6faa265a3d2085f9c13
```

Most of the anti-virus software don't report a virus.

If you don't trust the uploaded files, you can follow the README.md to compile the program.

**Comment by cr4zyfish** [comment]
This is because of golang.org/x/net/proxy package used in v 3.1. Windows defender detects it as virus.

**Comment by enfein** [comment]
@cr4zyfish Thank you for the information! It is possible to replace that dependency.

**Comment by wzmnge** [comment]
Thanks very much
