### ISSUE TITLE
没有特征不就是最大的特征

### ISSUE THREAD

**Issue by OVOJKzzZ** [enfein/mieru#14]

**Comment by OVOJKzzZ** [comment]
如题，欢迎来讨论

**Comment by OVOJKzzZ** [comment]
看完介绍，感觉跟 裸 VMess Tcp 没有什么区别

**Comment by Gaukas** [comment]
> 没有特征不就是最大的特征

It is exactly my concern. However here's an optimistic idea: https://github.com/enfein/mieru/issues/8#issuecomment-1166396070

**Comment by enfein** [comment]
不想花太多时间讨论这些争议性的话题。我的想法是，GFW 封杀无法归类的流量，付出的实际代价是比较大的。我们假设 GFW 使用类似随机森林的算法学习互联网的流量特征，来区分已知的协议和无法归类的协议。这些 AI 算法无论做得多好，都无法绕开两个问题。一是 AI 很难处理应当归类却没有见过的流量，二是 AI 的判定存在 false position 和 false negative。这将导致 GFW 如果开始大面积封杀无法归类的流量，势必会影响正常的网络服务，而这会对社会经济造成诸多影响。

在加速到底的路上，会有一天，圣上觉得为了保护政权，必须要付出一些经济的代价，那个时候，我们这些协议可能就会死掉了。模仿其他协议的代理未必会活得很好，一方面是他们各自有自己的弱点（TLS 不是为了翻墙设计的），另一方面，大洪水到来的时候，我们会变成朝鲜互联网，到了那个时候用什么工具就意义不大了。

mieru 和 VMess 有诸多不同之处。看起来两个都是随机字符串流，但是 mieru 在加密算法，密钥生成过程，随机填充这几方面有不一样的考虑。协议表面的相似性不代表实际对抗主动探测的能力相同。

**Comment by enfein** [comment]
Close after 14 days of inactivity.

**Comment by moranno** [comment]
请问作者，关于向前安全mieru是否有相关考虑和设计？

**Comment by enfein** [comment]
@moranno 

设计协议的时候我思考过这件事。我当时的结论是没有必要做向前安全。主要原因是，以现在的密钥生成算法和一个连接的生命周期，使用 AES-256-GCM 算法时，攻击者几乎不可能收集足够多的信息达成 plain text reveal 和 partial key recovery。假如 mieru 协议内部做了网络连接复用，那么向前安全会变得很有必要。
