### ISSUE TITLE
希望强化test功能

### ISSUE THREAD

**Issue by yatounoneko** [enfein/mieru#140]
`Get "https://google.com/generate_204": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`
這個錯誤出現在我從國外mieru向國内mita發送test的時候出現的問題，國内的服務器無法訪問這類測試網址。

請問是否可以自定義測試連接？
用途：海外回國。

**Comment by enfein** [comment]
没问题，可以加一个额外的参数让用户指定网址
