### ISSUE TITLE
DNS problem in android version

### ISSUE THREAD

**Issue by cr4zyfish** [enfein/mieru#141]
In the Android version of Mieru, is it possible to modify the plugin to resolve DNS remotely?

If we install Nekobox with the Mieru plugin, by default, only apps that directly connect to IP addresses work. We need to change DNS settings in Nekobox and use FakeDNS (which is buggy with Mieru), DirectDNS, etc., for all apps to work. Some of these settings introduce DNS leaks.

If modifying the Android plugin is not possible, then I think updating the documentation is required to explain how to securely set DNS settings.

**Comment by enfein** [comment]
mieru itself only resolve DNS remotely.

The NekoBox app or sing-box needs to be modified to pass the DNS to the plugin. There is nothing we can do at mieru side.
