### ISSUE TITLE
How do you write the such beautiful code?

### ISSUE THREAD

**Issue by juiiyang** [enfein/mieru#142]
我感觉这个设计太有才了：
`mita apply config <FILE>`
`mita describe config`

我想知道这个 config 被存到了哪个文件夹？
然后从 cmd 出发，一路找呀找，发现你写的代码真的太好看啦！
当然我也找到了它：`https://github.com/enfein/mieru/blob/main/pkg/appctl/client.go#L58`

请问一下，你是怎么写出这么优美的代码的？从工作经验练出来的 or 学习一些开源项目 or 其他？

**Comment by enfein** [comment]
过奖了。

我有几年时间主要使用 Golang 语言工作。

建议多看看优秀开源项目的代码，可以提高品味。例如这个 `mita apply config` 的设计是从 Kubernetes 那里学来的。

**Comment by juiiyang** [comment]
Thx
