### ISSUE TITLE
除了nekobox，安卓有没有其他客户端实现

### ISSUE THREAD

**Issue by bidabrain** [enfein/mieru#143]
mieru只有nekobox 1.3.1版本才支持，但是nekobox 1.3.1有bug容易杀后台进程。虽然nekobox1.2.9没有这个问题，但是又不支持mieru。 nekobox已经很久不更新了，有没有其他可以用的安装客户端？

**Comment by enfein** [comment]
很早之前 mieru 有 SagerNet 插件，后来大佬去做 sing-box 了，那个安卓客户端就废弃了。NekoBox 是 SagerNet 衍生品。如果 NekoBox 没有人维护，然后有大佬继续开发衍生品，我可以把 SagerNet 或 NekoBox 上面支持 mieru 的代码再搬过去。如果你知道有这种安卓客户端请告诉我。

**Comment by bidabrain** [comment]
> 很早之前 mieru 有 SagerNet 插件，后来大佬去做 sing-box 了，那个安卓客户端就废弃了。NekoBox 是 SagerNet 衍生品。如果 NekoBox 没有人维护，然后有大佬继续开发衍生品，我可以把 SagerNet 或 NekoBox 上面支持 mieru 的代码再搬过去。如果你知道有这种安卓客户端请告诉我。

sing-box现在有官方客户端SFA。这个有办法加入外挂内核支持mieru么？

**Comment by bidabrain** [comment]
> 很早之前 mieru 有 SagerNet 插件，后来大佬去做 sing-box 了，那个安卓客户端就废弃了。NekoBox 是 SagerNet 衍生品。如果 NekoBox 没有人维护，然后有大佬继续开发衍生品，我可以把 SagerNet 或 NekoBox 上面支持 mieru 的代码再搬过去。如果你知道有这种安卓客户端请告诉我。

发现一个fork nekobox继续开发的客户端 https://github.com/xchacha20-poly1305/husi

**Comment by enfein** [comment]
我之后去看一下

**Comment by enfein** [comment]
在 README 中增加了 Exclave 和 husi 项目。
