### ISSUE TITLE
能提供openbsd的mita二进制包么

### ISSUE THREAD

**Issue by bidabrain** [enfein/mieru#144]
想在serv00上跑。 或者能提供自己编译的方法么？

**Comment by enfein** [comment]
在项目根目录下运行

```shell
env GOOS=openbsd GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-s -w" -o mita cmd/mita/mita.go
```

之后，项目根目录下的 `mita` 文件就是服务器软件。

因为存在一些和平台绑定的代码，在 OpenBSD 上有可能无法正常工作。

**Comment by molezz** [comment]
> 想在serv00上跑。 或者能提供自己编译的方法么？

serv00 是 freebsd吧
` FreeBSD 14.1-RELEASE-p4 (devil) `
