### ISSUE TITLE
BSD操作系统代理支持

### ISSUE THREAD

**Issue by jujubeja** [enfein/mieru#148]
[GhostBSD](https://ghostbsd.org/)
[NomadBSD](https://nomadbsd.org/)
[OpenBSD](https://www.openbsd.org/)

[postmarketOS](https://postmarketos.org/) 手机linux

提供BSD mieru编译安装文档说明 或二进制包

**Comment by enfein** [comment]
和 issue #144 类似，不过这次编译的是客户端

```
env GOOS=openbsd GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-s -w" -o mieru cmd/mieru/mieru.go
```

Go 语言好像不支持 GhostBSD 和 NomadBSD。不如如果它们的系统调用和某个支持的 BSD 相互兼容，例如 FreeBSD，那么可执行文件也是能够运行的。
