### ISSUE TITLE
Start mieru at system boot

### ISSUE THREAD

**Issue by Gitscarlet** [enfein/mieru#149]
I have ubuntu 22 mieru is not started at system boot so I created this systemd file:

```
[Unit]
Description=Run mieru after boot
After=network.target

[Service]
ExecStartPre=/bin/sleep 60
ExecStart=/usr/bin/mieru start

[Install]
WantedBy=default.target
```

but it is not working:

`get mieru client config failed: clientConfigFilePath() failed: prepareClientConfigDir() failed: neither $XDG_CONFIG_HOME nor $HOME are defined`

when i manually run `mieru start` it works. but with systemd it gives error. how to solve this?

**Comment by enfein** [comment]
The `mieru start` command will fork another process and then exit. This will make systemd confused. With systemd, I recommend using `mieru run` command with `MIERU_CONFIG_JSON_FILE` environment variable to specify the mieru configuration.

You can see the example in https://github.com/enfein/mieru/blob/main/configs/examples/mieru.service
