### ISSUE TITLE
关于新版本v3.2.1

### ISSUE THREAD

**Issue by yyuurrii34** [enfein/mieru#152]
这个项目的最新版v3.2.1中，这段更新内容描述:
"将加密随机数前缀从可打印字符进一步限定至 [0-9A-Za-z_-]。"
是否符合这篇论文提到的[GFW豁免规则？](https://gfw.report/publications/usenixsecurity23/zh/#sec:ascii-exemption)

**Comment by enfein** [comment]
关于那篇论文提到的规则，我们在 [v1.14.0](https://github.com/enfein/mieru/releases/tag/v1.14.0) 版本就已经实装了。

v3.2.1 版本在那个基础上做了一些修改。

**Comment by yyuurrii34** [comment]
客户端mieru在本地监听时，可否同时监听ipv6？类似这样，
listen=[::]:8888 或  [::1]:8888

**Comment by yyuurrii34** [comment]
另外，你的release内空包含安卓系统的压缩包，解压后是单个可执行文件。请问要怎么在安卓手机上安装?

**Comment by yyuurrii34** [comment]
> 关于那篇论文提到的规则，我们在 [v1.14.0](https://github.com/enfein/mieru/releases/tag/v1.14.0) 版本就已经实装了。
> 
> v3.2.1 版本在那个基础上做了一些修改。

请问将ASCII字符限制在一定范围是否增加协议特征性风险？

**Comment by enfein** [comment]
> 客户端mieru在本地监听时，可否同时监听ipv6

Linux 如果设置了双网络栈，会同时监听 ipv4 和 ipv6. 其他系统还不支持。

**Comment by enfein** [comment]
> 另外，你的release内空包含安卓系统的压缩包，解压后是单个可执行文件。请问要怎么在安卓手机上安装?

去 https://github.com/enfein/NekoBoxPlugins 下载 apk 文件。

**Comment by enfein** [comment]
> 请问将ASCII字符限制在一定范围是否增加协议特征性风险？

如果是 SS 或者 v2ray 肯定不能直接这么改。mieru 用的人少，我估计 GFW 没有那么多经费做适配。而且这个东西不属于 mieru 协议，之后的版本随时可以改掉。
