### ISSUE TITLE
感谢大佬

### ISSUE THREAD

**Issue by xiaopangzi13140** [enfein/mieru#153]
谢谢大佬，没想到win7系统也可用。

**Comment by enfein** [comment]
Golang 1.20 是最后一个支持 win7 的编译器，现在已经不更新了。或许明年这个项目不得不放弃对 win7 的支持。

**Comment by xiaopangzi13140** [comment]
好的。希望到时候可以标注下，比如适合win7的最后一个版本号是多少。感谢。
