### ISSUE TITLE
3.3.0 安装失败，影响 Debian 11 和以下的系统

### ISSUE THREAD

**Issue by xiaopangzi13140** [enfein/mieru#154]
root:~# dpkg -i mita_3.3.0_amd64.deb
dpkg-deb: error: archive 'mita_3.3.0_amd64.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive mita_3.3.0_amd64.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 mita_3.3.0_amd64.deb

**Comment by enfein** [comment]
deb 包的默认压缩格式从 xz 改成了 zstd, Debian 版本小于 12 的系统会遇到这个问题。

**Comment by enfein** [comment]
v3.3.1 修复了这个问题

**Comment by xiaopangzi13140** [comment]
谢谢。v3.3.1可以正常安装了。

**Comment by xiaopangzi13140** [comment]
请问udp协议是跟hy一样用的quic协议吗？

**Comment by enfein** [comment]
是自研的协议 https://github.com/enfein/mieru/blob/main/docs/protocol.zh_CN.md
