### ISSUE TITLE
客户端与服务端的版本是否必须一致？

### ISSUE THREAD

**Issue by U201413497** [enfein/mieru#155]
情况说明：服务端，debian12，最新的3.3.1版本，vps是Ipv6小鸡

客户端，windows11 最新的3.3.1版本，可以使用
              安卓，NekoBox，mieru插件，3.3.0版本，无法使用。使用ipv6地址和Ipv6绑定的域名，都不行。

**Comment by enfein** [comment]
不需要。大版本号相同即可，建议服务器版本大于等于客户端版本。

3.3.0 和 3.3.1 几乎没有任何区别。听上去是 NekoBox 处理 ipv6 有问题。
