### ISSUE TITLE
作为ssh代理时会自动断开，网络不稳定

### ISSUE THREAD

**Issue by U201413497** [enfein/mieru#156]
环境：vps小鸡，debian12，ipv6 only，mita版本3.3.1，tcp 5000端口

客户端，win11，版本3.3.1 ，设置了一个127.0.0.1 1080的socks5入

使用ssh客户端，连接时使用了127.0.0.1 1080的socks5代理，ssh能够连接ipv6小鸡，几个小鸡都是几秒钟自动断开ssh连接。

使用naiveproxy等客户端时，同样127.0.0.1 1080的socks5入，连接ssh后稳定，不会断开。mieru协议为何会这样呢？

**Comment by enfein** [comment]
打开客户端和服务器的调试日志，看看是谁切断的连接

https://github.com/enfein/mieru/blob/main/docs/operation.zh_CN.md#%E6%89%93%E5%BC%80%E5%92%8C%E5%85%B3%E9%97%AD%E8%B0%83%E8%AF%95%E6%97%A5%E5%BF%97

此外，连接断开后，能否分享 `mieru get metrics` 的输出？

**Comment by enfein** [comment]
另外，你是怎样使 ssh 客户端接入 socks5 代理的？

**Comment by enfein** [comment]
我在 Linux 上没有遇到类似的问题

```sh
ssh -o ProxyCommand='nc -X 5 -x 127.0.0.1:1080 %h %p' USERNAME@MY_SERVER
```
