### ISSUE TITLE
version 3.4.0 looks buggy

### ISSUE THREAD

**Issue by cr4zyfish** [enfein/mieru#158]
I have a SOCKS5 proxy that is working:
`curl --socks5 <username>:<password>@<proxy_address>:<port> http://example.com`

However, the features in the new update do not work for me. Has anyone tested them?

Using the [example configs](https://github.com/enfein/mieru/tree/main/configs/examples), When I set the outbound proxy on the server, I receive the following error in the client browser:
```
Unable to connect

An error occurred during a connection to www.google.com.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the web.
```

If I use authentication in the client configuration, it does not work, and I get this error:
```
The proxy server is refusing connections

An error occurred during a connection to www.google.com.

    Check the proxy settings to make sure that they are correct.
    Contact your network administrator to ensure the proxy server is working.
```
Additionally, if I apply the old configuration that does not use authentication, the SOCKS5 authentication is still present, and I need to enter additional commands to clear it:

`mieru delete socks5 authentication`

After applying the old configuration, I still experience connection issues, and Mieru sometimes does not work.
I downgraded to version 3.3.3 . it is more stable now.

**Comment by enfein** [comment]
@cr4zyfish

Please follow the user guide. If you don't connect to another proxy, don't use outbound proxy. If you connect to another proxy from mita, only add socks5 authentication in server config, when the next proxy support socks5 authentication.

In my case, I don't use outbound proxy. Here is my client config:

```
$ mieru describe config
{
    ...
    "socks5Port": 1080,
    "loggingLevel": "DEBUG",
    "socks5ListenLAN": false,
    "socks5Authentication": [
        {
            "user": "yitukai",
            "password": "manlianpenfen"
        },
        {
            "user": "shilishanlu",
            "password": "buhuanjian"
        }
    ]
}
```

And socks5 authentication works well

```
$ curl --socks5 shilishanlu:buhuanjian@127.0.0.1:1080 http://example.com
<!doctype html>
<html>
...
<body>
<div>
    <h1>Example Domain</h1>
    <p>This domain is for use in illustrative examples in documents. You may use this
    domain in literature without prior coordination or asking for permission.</p>
    <p><a href="https://www.iana.org/domains/example">More information...</a></p>
</div>
</body>
</html>
```

**Comment by cr4zyfish** [comment]
Why there are two users here?
```

        {
            "user": "yitukai",
            "password": "manlianpenfen"
        },
        {
            "user": "shilishanlu",
            "password": "buhuanjian"
        }
```

**Comment by cr4zyfish** [comment]
My problem for mieru was:
`socks5 username and password authentication is not compatible with HTTP / HTTPS proxy.`
I was using both in my config and because im using my mieru gui app i didn't see this error. 
however i still need to find problem of server with egress.
