### ISSUE TITLE
Proposal: support for front proxy in mieru client

### ISSUE THREAD

**Issue by Anvor-coll** [enfein/mieru#159]
I would like to propose the addition of front proxy support to the Mieru client, specifically an HTTP proxy. Because I would prefer to avoid connecting directly to Mita server.

**Comment by enfein** [comment]
The traffic between mieru and mita is already encrypted, what is the benefit you want to get by adding another proxy in this path?

**Comment by Anvor-coll** [comment]
> The traffic between mieru and mita is already encrypted, what is the benefit you want to get by adding another proxy in this path?

By using a front proxy, the client’s real IP address can be hidden. It can also be used to bypass local gateway in some networks with strict traffic monitoring. For example, if a gateway blocks certain computers from accessing the internet or censors traffic, but allows mobile traffic, connecting to Mita server via a mobile device's HTTP proxy can bypass these restrictions.

**Comment by enfein** [comment]
> By using a front proxy, the client’s real IP address can be hidden.

The client IP is hidden as long as a proxy is used, not necessarily a front proxy.

> It can also be used to bypass local gateway in some networks with strict traffic monitoring.

mieru is designed to pass GFW. In your case, I suggest using another tool like singbox to pass the local network, then connect to mieru to across the GFW.
