### ISSUE TITLE
麻烦大佬支持适配下mihomo（clash.meta）客户端代理工具

### ISSUE THREAD

**Issue by powerjiayun** [enfein/mieru#161]
平时主要在用clash客户端，麻烦大佬支持适配下mihomo（clash.meta）客户端代理工具

https://github.com/MetaCubeX/mihomo/tree/Meta?tab=readme-ov-file
https://wiki.metacubex.one/

**Comment by enfein** [comment]
直接将 mieru 协议集成至 clash 内核需要花一些时间。在此之前，可以将 mieru 作为 clash 的前置代理使用。

**Comment by enfein** [comment]
根据 mihomo 开发者的反馈，还有比较多的事情要做，目前没有预估的期限。

**Comment by powerjiayun** [comment]
好的，谢谢大佬

**Comment by yesiamchinese** [comment]
Would you please release a simple mieru verion that can be managed by systemd easily ?

A simple verion only support a few simple command, such as :
mieru -c /etc/mieru/config.json # run and start with config file /etc/meru/config.json

So, we can prepare many mieru socks service for mihomo:
mieru -c /etc/mieru/server1.json # provide service in socks 1080
mieru -c /etc/mieru/server2.json # provide service in socks 1081
......

You can see naiveproxy, hysteria(2) is very simple.

**Comment by enfein** [comment]
代码已经合并到 mihomo 仓库。第一个版本只支持 TCP 协议。
