### ISSUE TITLE
curl: (18) transfer closed with 1600 bytes remaining to read

### ISSUE THREAD

**Issue by shiqishao** [enfein/mieru#168]
mita版本：3.7.0 运行在ubuntu20.04上
mieru版本：3.7.0 运行在ubuntu20.04上

当我启动mieru后，运行如下命令会报错：
`curl --proxy socks5://127.0.0.1:1080 http://new2.setn.top`
报错信息：
`curl: (18) transfer closed with 1600 bytes remaining to read`

我该如何解决此问题？谢谢！

**Comment by enfein** [comment]
应该是 bug 导致数据在完全写入之前关闭了网络连接。

**Comment by enfein** [comment]
具体的问题应该是这样的：

大多数网站使用 HTTP keep alive，如果浏览器不关闭连接，服务器是不会关闭连接的。

这个上古网站行为不一样，在 HTTP 返回之后主动关闭网络连接。mieru 客户端收到关闭网络连接的请求之后会垃圾回收所有数据，如果这些数据还没有被 curl 取走，就会丢失。

**Comment by shiqishao** [comment]
> 具体的问题应该是这样的：
> 
> 大多数网站使用 HTTP keep alive，如果浏览器不关闭连接，服务器是不会关闭连接的。
> 
> 这个上古网站行为不一样，在 HTTP 返回之后主动关闭网络连接。mieru 客户端收到关闭网络连接的请求之后会垃圾回收所有数据，如果这些数据还没有被 curl 取走，就会丢失。
感谢大佬解惑

**Comment by enfein** [comment]
v3.8.0 修复了这个问题。
