### ISSUE TITLE
为什么不能使用命令行加配置文件直接启动服务？

### ISSUE THREAD

**Issue by pfangzhi** [enfein/mieru#175]
为什么不能使用命令行加配置文件直接启动服务？这样很方便的部署程序，修改配置等都会更方便。

**Comment by enfein** [comment]
设计用户接口的时候主要考虑的是命令行交互。

命令行加配置文件直接启动服务是可以做到的，不过需要使用环境变量。例如

```shell
MIERU_CONFIG_JSON_FILE=/etc/mieru_client_config.json mieru run
```

参考

- https://github.com/enfein/mieru/blob/main/configs/examples/mieru.service
- https://github.com/enfein/mieru/blob/main/docs/operation.zh_CN.md#%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F

**Comment by enfein** [comment]
还有一个小问题，使用环境变量 `MIERU_CONFIG_JSON_FILE` 运行 `mieru run` 依旧会把日志写到文件而不是 stdout. 之后的版本会修复这个问题。

**Comment by yjd** [comment]
今天第一次使用确实不像大多数那么方便。我其他都是命令行启动和配置，统一放在一个文件夹下(迁移也方便tar拷贝解压搞定)，写个sh来维护还可以./run update|cmd
现在两端想看个日志都挺麻烦，看了下文档需要打一些命令

**Comment by enfein** [comment]
@yjd

我正好是因为讨厌命令行指定配置文件的做法，才在 mieru 选择了不一样的用户交互模式。命令行+配置文件做法有这样几个问题：

1. 服务器端需要手搓一个 systemd 服务出来，没办法开箱即用。
2. 客户端如果忘记重定向日志到文件，日志总是因为终端显示行数有上限而看不到。
3. 没有办法实时获取运行信息。

另外，这里提供的解决方案 https://github.com/enfein/mieru/blob/main/docs/operation.zh_CN.md#%E5%9C%A8%E5%89%8D%E5%8F%B0%E8%BF%90%E8%A1%8C%E5%AE%A2%E6%88%B7%E7%AB%AF 已经非常接近于命令行指定配置文件了。当然，使用这种方法会继承上述的缺点 2 和 3。

为了避免提供太多选择迷惑用户，现在暂时没有打算更改这方面的用户交互方式。

**Comment by yjd** [comment]
1. 正好相反，不喜欢安装，喜欢文件放哪清清楚楚。我知道systemd 服务更现代更好。
     但我需求不高。直接cron+脚本。纯绿色不安装。
2. 日志一般是开始用的时候调试观看，测试成功后。平常也没再看一跑就一年。最多升级升级版本。
      其他的代理默认运行是 ( nohup ${run} >>llog.txt 2>&1 & ) 只有要观看才前台运行
3. 如上面 tail -n xx -f llog.txt 实时观看

目前也只能按文档跑服务了。

**Comment by enfein** [comment]
@yjd 没有一种设计能让所有人都满意。这个项目使用了不那么常见的设计思路，希望为用户提供另一种可能。

**Comment by yjd** [comment]
@enfein 

1， 初始运行，正常能监听端口，会提示一行错误，因为metrics.pb还没创建。
&nbsp;&nbsp;&nbsp;&nbsp; `export MITA_CONFIG_JSON_FILE=/x-Force/mita/ser.json;./mita run`

> INFO Failed to load previous metrics: os.ReadFile("/var/lib/mita/metrics.pb") failed: open /var/lib/mita/metrics.pb: no such file or directory

2，追加设置 MITA_CONFIG_FILE 路径程序就跑不起来，同样提示上面的错误，但程序没有监听端口。
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;unset MITA_CONFIG_FILE 后又可以正常运行和监听端口。
`export MITA_CONFIG_JSON_FILE=/x-Force/mita/ser.json;export MITA_CONFIG_FILE=/x-Force/mita/metrics.pb;./mita run`

**Comment by enfein** [comment]
@yjd 

`/var/lib/mita/metrics.pb` 用来存放指标而不是配置。所以这一行是 INFO 不是 ERROR。程序启动一段时间之后会写入这个文件，之后就不会打印这一行信息了。

用 `MITA_CONFIG_JSON_FILE` 指向 JSON 配置文件，用 `MITA_CONFIG_FILE` 指向 protobuf 配置文件。如果两个都不指定，默认等于使用 `MITA_CONFIG_FILE=/etc/mita/server.conf.pb`。

请参考文档 https://github.com/enfein/mieru/blob/main/docs/operation.zh_CN.md#%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F

**Comment by yjd** [comment]
谢谢！理解错了，以为MITA_CONFIG_FILE是定义指标文件路径。。。

**Comment by pfangzhi** [comment]
我的服务器是用的openwrt，离了命令行，我还 真不知道咋配置才能运行起来，所以目前想用但是只能放弃

**Comment by yjd** [comment]
> 我的服务器是用的openwrt，离了命令行，我还 真不知道咋配置才能运行起来，所以目前想用但是只能放弃

按上面作者的回复就可以跑命令行。我目前就是特意把服务删了。解包出文件，单独跑命令行加载。不过目前看cpu占比其他的要占用高点。hy>mieru>na

**Comment by yjd** [comment]
@enfein 
请教下，有多台目的服 a，b 
目前在一台win上做成2个配置文件，配置中
```
a.json:
"profileName": "a"
"activeProfile": "a"
```
```
b.json：
"profileName": "b"
"activeProfile": "b"
```
批处理先 
```
set MIERU_CONFIG_JSON_FILE=a.json 
mieru.exe run
```
```
set MIERU_CONFIG_JSON_FILE=b.json 
mieru.exe run
```
运行起立没问题。但如果要看 get metrics 和 get connections 就有点麻烦，也是要先设置MIERU_CONFIG_JSON_FILE 再执行命令，当然再弄个批处理也算解决。算是个小问题，平常也很少看这两个数据。
看文档好像也没有整合成1个配置文件的方法，或指定不同端口走a或b服务器。我切换是直接浏览器 SwitchyOmega 直接选端口

**Comment by enfein** [comment]
@yjd 一个 profile 可以指定多台服务器，客户端配置再加一台服务器到 JSON 数组即可。因为客户端只监听一个 socks5 或者 HTTP 端口，没有办法实现多个服务器之间的分流。需要高级功能可以考虑 mihomo 客户端。

**Comment by happytrudy** [comment]
s6运行需要命令行 大哥

**Comment by enfein** [comment]
@happytrudy s6 是什么？

另外

```
MIERU_CONFIG_JSON_FILE=/etc/mieru_client_config.json mieru run
```

这种方式应该可以

**Comment by happytrudy** [comment]
s6 overlay
容器用的是这个 如果是宿主机用s6用来管理服务 替代systemctl更加轻量方便移植 服务器崩溃重装更快
我看了服务端用命令行非常麻烦 首先要创建mita socket文件夹  然后在创建用户mita 并指定当前bin目录权限 最后运行命令行 所以问下能不能不要这么麻烦 有直接运行bin的命令行吗
我知道安全性考虑建立用户，但是不强制可以吗，其实nginx也有这种考虑但是root下也可以运行

**Comment by yjd** [comment]
@happytrudy  可以参考
```bash
#!/usr/bin/env bash
cd `dirname $0`
#-------------------------------------------------------------
add_user() {
USERNAME="mita"

if ! id "$USERNAME" &>/dev/null; then
    echo "用户 $USERNAME 不存在，正在创建..."
    useradd "$USERNAME"
    if id "$USERNAME" &>/dev/null; then
        echo "用户 $USERNAME 创建成功"
    else
        echo "用户 $USERNAME 创建失败"
    fi
fi
}
add_user

create_dir() {
    TARGET_DIR="/var/run/mita"
    if [ ! -d "$TARGET_DIR" ]; then
        if mkdir -p "$TARGET_DIR"; then
            echo "目录 $TARGET_DIR 创建成功。"
        else
            echo "错误：无法创建目录 $TARGET_DIR。请检查权限或联系系统管理员。"
        fi
    fi

    TARGET_DIR="/var/lib/mita"
    if [ ! -d "$TARGET_DIR" ]; then
        if mkdir -p "$TARGET_DIR"; then
            chmod 777 $TARGET_DIR
            touch "$TARGET_DIR"/metrics.pb
            echo "目录 $TARGET_DIR 创建成功。"
        else
            echo "错误：无法创建目录 $TARGET_DIR。请检查权限或联系系统管理员。"
        fi
    fi

    TARGET_DIR="/var/lib/mita"
    METRICS_FILE="$TARGET_DIR/metrics.pb"
    if [ ! -f "$METRICS_FILE" ]; then
        if touch "$METRICS_FILE" && chmod 777 "$METRICS_FILE"; then
            echo "文件 $METRICS_FILE 创建成功。"
        else
            echo "错误：无法创建文件 $METRICS_FILE。请检查权限或联系系统管理员。"
        fi
    fi
}
create_dir
#-------------------------------------------------------------
export MITA_CONFIG_JSON_FILE=`pwd`/ss.json

appName='mita'
canshu=' run'

exeCmd=`pwd`'/'${appName}
run=${exeCmd}${canshu}

if [[ $1 = "?" ]]; then
    echo "$0 lj  //get connections"
    echo "$0 tj  //get metrics"
    exit
fi

if [[ $1 = "lj" ]]; then
    ${exeCmd} get connections
    exit
fi

if [[ $1 = "tj" ]]; then
    ${exeCmd} get metrics
    exit
fi

pkill -f ${exeCmd}

if [[ $1 = "cmd" ]]; then
    ${run} "${@:2}"
    exit
fi

nohup ${run} >>llog.txt 2>&1&
exit 0

```

**Comment by happytrudy** [comment]
我直接用mihomo了@yjd
