### ISSUE TITLE
meiru failed to install on debian12 correctly

### ISSUE THREAD

**Issue by wnpllrzodiac** [enfein/mieru#179]
dpkg -i mieru_3.9.0_amd64.deb
(Reading database ... 42004 files and directories currently installed.)
Preparing to unpack mieru_3.9.0_amd64.deb ...
Unpacking mieru (3.9.0) over (3.9.0) ...
Setting up mieru (3.9.0) ...

sudo usermod -a -G mita $USER
group 'mita' does not exist

os: debian12
arch: amd64

**Comment by enfein** [comment]
If you are setting up proxy server, please install `mita_3.9.0_amd64.deb` rather than `mieru_3.9.0_amd64.deb`.

**Comment by wnpllrzodiac** [comment]
Thanks
