### ISSUE TITLE
Udp Associate support for socks5?

### ISSUE THREAD

**Issue by hdid** [enfein/mieru#20]
Is it possible to add this feature for handling udp datagrams?

**Comment by enfein** [comment]
Will do.

**Comment by enfein** [comment]
Considering the benefits and the size of the feature, I expect this won't be implemented in a short time. My current priority is safety (unable to detect) and network speed.

**Comment by enfein** [comment]
Youtube android app is using this. Have to prioritize this feature. Target to get one working solution in 1.7.0 or 1.8.0.
