### ISSUE TITLE
It cannot be used

### ISSUE THREAD

**Issue by V70024** [enfein/mieru#24]
### I have done all the configuration correctly and it worked fine for a few hours but then it completely stopped working.
_(During the few hours it worked, it did not open youtube.com)_

**I searched a lot for the problem but did not find it** 

--------------------

┌─[root@id-531791]─[~]
└──╼ #`cat mieru/configs/templates/server_config.jso`

```
{
    "portBindings": [
        {
            "port": 20,
            "protocol": "TCP"
        }
    ],
    "users": [
        {
            "name": "user",
            "password": "password"
        }
    ],
    "loggingLevel": "INFO",
    "mtu": 1375
}
```
--------------------
┌─[root@id-531791]─[~]
└──╼ #`mita describe config`

```

{
    "portBindings":  [
        {
            "port":  20,
            "protocol":  "TCP"
        }
    ],
    "users":  [
        {
            "name":  "user",
            "hashedPassword":  "bc246cd4...............4b1cf9933e"
        }
    ],
    "loggingLevel":  "INFO",
    "mtu":  1375
}

```

--------------------
┌─[root@id-531791]─[~]
└──╼ #`mita start`
```
mieru server proxy is running
```

--------------------

┌─[root@id-531791]─[~]
└──╼ #`mita status`
```
mieru server status is "RUNNING"
```

--------------------

┌─[root@id-531791]─[~]
└──╼ #`systemctl status mita.service `
```
● mita.service - Mieru proxy server
     Loaded: loaded (/lib/systemd/system/mita.service; enabled; vendor preset: disabled)
     Active: active (running) since Mon 2022-07-25 22:55:46 CEST; 1h 40min ago
   Main PID: 7387 (mita)
      Tasks: 5 (limit: 2269)
     Memory: 3.4M
        CPU: 1.029s
     CGroup: /system.slice/mita.service
             └─7387 /usr/bin/mita run

Jul 26 00:35:46 id-531791 mita[7387]: 2022-07-26T00:35:46+02:00 INFO [metrics - client decryption] ClientDirectDecrypt=0 ClientFailedDirectDecrypt=0
Jul 26 00:35:46 id-531791 mita[7387]: 2022-07-26T00:35:46+02:00 INFO [metrics - UDP packets] InPkts=0 OutPkts=0
Jul 26 00:35:46 id-531791 mita[7387]: 2022-07-26T00:35:46+02:00 INFO [metrics - KCP segments] EarlyRetransSegs=0 FastRetransSegs=0 InSegs=0 LostSegs=0 OutOfWindowSegs=0 OutSegs=0 RepeatSegs=0 RetransSegs=0
Jul 26 00:35:46 id-531791 mita[7387]: 2022-07-26T00:35:46+02:00 INFO [metrics - UDP bytes] InBytes=0 OutBytes=0
Jul 26 00:35:46 id-531791 mita[7387]: 2022-07-26T00:35:46+02:00 INFO [metrics - KCP bytes] BytesReceived=0 BytesSent=0 PaddingSent=0
Jul 26 00:35:46 id-531791 mita[7387]: 2022-07-26T00:35:46+02:00 INFO [metrics - TCP bytes] InBytes=990 OutBytes=0 PaddingSent=0
Jul 26 00:35:46 id-531791 mita[7387]: 2022-07-26T00:35:46+02:00 INFO [metrics - replay protection] ReplayKnownSession=0 ReplayNewSession=0
Jul 26 00:35:46 id-531791 mita[7387]: 2022-07-26T00:35:46+02:00 INFO [metrics - UDP errors] KCPInErrors=0 KCPReceiveErrors=0 KCPSendErrors=0 UDPInErrors=0
Jul 26 00:35:46 id-531791 mita[7387]: 2022-07-26T00:35:46+02:00 INFO [metrics - TCP errors] TCPReceiveErrors=63 TCPSendErrors=0
Jul 26 00:35:46 id-531791 mita[7387]: 2022-07-26T00:35:46+02:00 INFO [metrics - server socks5 errors] ConnectionRefused=0 DNSResolveErrors=0 HandshakeErrors=63 HostUnreachable=0 NetworkUnreachable=0 UnsupportedCommand=0

```
--------------------

┌─[root@id-531791]─[~]
└──╼ #`netstat -lntup | grep " LISTEN " | grep "20"`
```
tcp6       0      0 :::20                   :::*                    LISTEN      7387/mita           
```
--------------------
┌─[root@id-531791]─[~]
└──╼ #`firewall-cmd --zone=public --list-ports `
```
3389/tcp 22/tcp  20/tcp
```
--------------------
--------------------

┌─[vlad@70024]─[~]
└──╼ $`curl -U "<Username>:<Password>" -x <server ip>:20 httpbin.org/ip`
```
curl: (52) Empty reply from server
```

**Comment by enfein** [comment]
> it worked fine for a few hours

You tested something else rather than `curl`, right?

---

Everything you showed me about the server configuration is correct. Using port <= 1024 is discouraged but should work since mita run as root. The `curl` command you showed is problematic.

Mieru proxy contains two programs. A client called `mieru` is running in your local computer, and a server called `mita` is running in a remote computer. When you have both client and server configured and running, you use the socks5 port exposed from the **client** to create a network connection that goes through the proxy.

Let's say that in your client configuration, you set `socks5Port` to 2000, then you should use the following command

```
curl -x socks5://localhost:2000 httpbin.org/ip
```

Notice: you don't need to provide username and password, and you have to specify socks5 as the protocol.

That command works on my machine.

**Comment by qeatzy** [comment]
@V70024 
This is how i debug setup & connectivity issue. https://github.com/enfein/mieru/issues/18
To recap

**debug server** 
```
# mita describe config
# netstat -lnpt
```

**debug client**
```
$ mieru describe config
$ netstat -lnpt
```

**debug the socks server (aka, mieru, counterpart of sslocal in shadowsocks terminology)**
```
curl -x socks5h://127.0.0.1:1080 -o /dev/null http://cachefly.cachefly.net/100mb.test
```
replace 1080 with `socks5Port` number in output of `mieru describe config`
if mieru not run in localhost, replace 127.0.0.1 accordingly.

**Comment by V70024** [comment]
### I have a "`squid`" service running on my server, the "`squid`" service is running on port `3128`
### My "`mieru`" server is also running on port `20`

----
#### service  squid
┌─[root@id-531791]─[~]
└──╼ #`curl -U "user:password" -x 127.0.0.1:3128 -o /dev/null http://cachefly.cachefly.net/100mb.test`
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  100M  100  100M    0     0  72.5M      0  0:00:01  0:00:01 --:--:-- 72.5M
```
----
#### service  mieru
┌─[root@id-531791]─[~]
└──╼ #`curl -U "user:password" -x 127.0.0.1:20 -o /dev/null http://cachefly.cachefly.net/100mb.test`
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (52) Empty reply from server
```

**Comment by V70024** [comment]
I disabled the `mite.service` using `systemctl` and restarted the server.

┌─[root@id-531791]─[~]
└──╼ #`mita status`
```
get mieru server status failed: ServerLifecycleService.GetStatus() failed: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /var/run/mita.sock: connect: no such file or directory"
```

**Comment by V70024** [comment]
### I made the mentioned changes
----
#### First, I deleted the username and password
┌─[root@id-531791]─[~]
└──╼ #`mita describe config`
```
{
    "portBindings":  [
        {
            "port":  1080,
            "protocol":  "TCP"
        }
    ],
    "loggingLevel":  "INFO",
    "mtu":  1375
}
```
#### Then I opened port 1080 in firewall-cmd
┌─[root@id-531791]─[~]
└──╼ #`firewall-cmd --zone=public --list-ports `
```
3389/tcp 22/tcp 3350/tcp 25565/tcp 1080/tcp
```
#### After that, I made sure that the `mita.service` service is active
┌─[root@id-531791]─[~]
└──╼ #`systemctl status mita.service `
```
● mita.service - Mieru proxy server
     Loaded: loaded (/lib/systemd/system/mita.service; enabled; vendor preset: disabled)
     Active: active (running) since Tue 2022-07-26 18:17:57 CEST; 3h 37min ago
   Main PID: 677 (mita)
      Tasks: 6 (limit: 2269)
     Memory: 11.8M
        CPU: 223ms
     CGroup: /system.slice/mita.service
             └─677 /usr/bin/mita run

Jul 26 21:54:57 id-531791 mita[677]: 2022-07-26T21:54:57+02:00 INFO [metrics - client decryption] ClientDirectDecrypt=0 ClientFailedDirectDecrypt=0
Jul 26 21:54:57 id-531791 mita[677]: 2022-07-26T21:54:57+02:00 INFO [metrics - UDP packets] InPkts=0 OutPkts=0
Jul 26 21:54:57 id-531791 mita[677]: 2022-07-26T21:54:57+02:00 INFO [metrics - KCP segments] EarlyRetransSegs=0 FastRetransSegs=0 InSegs=0 LostSegs=0 OutOfWindowSegs=0 OutSegs=0 RepeatSegs=0 RetransSegs=0
Jul 26 21:54:57 id-531791 mita[677]: 2022-07-26T21:54:57+02:00 INFO [metrics - UDP bytes] InBytes=0 OutBytes=0
Jul 26 21:54:57 id-531791 mita[677]: 2022-07-26T21:54:57+02:00 INFO [metrics - KCP bytes] BytesReceived=0 BytesSent=0 PaddingSent=0
Jul 26 21:54:57 id-531791 mita[677]: 2022-07-26T21:54:57+02:00 INFO [metrics - TCP bytes] InBytes=150 OutBytes=0 PaddingSent=0
Jul 26 21:54:57 id-531791 mita[677]: 2022-07-26T21:54:57+02:00 INFO [metrics - replay protection] ReplayKnownSession=0 ReplayNewSession=0
Jul 26 21:54:57 id-531791 mita[677]: 2022-07-26T21:54:57+02:00 INFO [metrics - UDP errors] KCPInErrors=0 KCPReceiveErrors=0 KCPSendErrors=0 UDPInErrors=0
Jul 26 21:54:57 id-531791 mita[677]: 2022-07-26T21:54:57+02:00 INFO [metrics - TCP errors] TCPReceiveErrors=13 TCPSendErrors=0
Jul 26 21:54:57 id-531791 mita[677]: 2022-07-26T21:54:57+02:00 INFO [metrics - server socks5 errors] ConnectionRefused=0 DNSResolveErrors=0 HandshakeErrors=13 HostUnreachable=0 NetworkUnreachable=0 UnsupportedCommand=0
```
#### It was here that I realized that there is a problem in the output logs of the `systemctl status mita.service` command
#### Therefore, I once again used the `mita` service itself to find out the status of its activity

┌─[root@id-531791]─[~]
└──╼ #`mita status`
```
mieru server status is "RUNNING"
```
#### I do not understand this problem. Maybe this is my whole problem
#### So I went to test the service with `curl`.

#### I waited for almost 3 minutes because I didn't get any output, so I ended the operation with `ctrl+c` key
#### I used the command `time` at the beginning of the command to know the time spent on this operation
┌─[root@id-531791]─[~]
└──╼ #`time curl -x socks5h://127.0.0.1:1080 -o /dev/null http://cachefly.cachefly.net/100mb.test`
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^C

real	2m34.783s
user	0m0.008s
sys	0m0.004s
```
#### And again with a new layout in `curl` I restarted the test
#### This time I encountered the same output again
┌─[root@id-531791]─[~]
└──╼ #`curl -x 127.0.0.1:1080 -o /dev/null http://cachefly.cachefly.net/100mb.test`
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
curl: (52) Empty reply from server
```

**Comment by enfein** [comment]
@V70024 

I believe you didn't understand what I previously talked about. In my previous comment, I mentioned two things.

First, we have a client program called mieru and a server program called mita. You need to have **both** configured correctly and running. The client program runs in your local computer and the server program runs in a computer outside GFW. **Please follow the tutorial again** to set up your server program and client program, before doing any testing with curl. You can directly copy the example configurations provided in the tutorial.

Second, when using `curl -x`, make sure you set protocol to socks5 with `socks5://` or `socks5h://`, otherwise it will never work. The proxy address of curl is localhost:socks5Port, where the socks5Port is set in the client configuration.

Assume your server and client configuration set `portBindings` -> `port` to 20, and in your client configuration `socks5Port` is set to 2000, then you should be able to use the following command.

```
curl -x socks5://localhost:2000 httpbin.org/ip
```

If it doesn't work, please show the output of the following commands in your next comment.

In your server computer:

- mita status
- mita describe config

In your client computer:

- mieru status
- mieru describe config

**Comment by V70024** [comment]
My problem is solved. My main problem was that I did not have `Client` active on my system and I thought that only `Server` was enough.

Even though I was wrong, thank you for taking the time to explain to me calmly

A question that occurred to me is why `systemctl` is not supported in `client‍`?

**Comment by enfein** [comment]
> A question that occurred to me is why systemctl is not supported in client‍?

systemd is used by the mita server to start the server automatically after the computer boot.

We don't use systemd in the client, because our client can run in Windows and macOS where systemd is absent, and I don't think start the client automatically after boot is mandatory. If you need that, you can write your own systemd service.
