### ISSUE TITLE
socks5 handshake might break if the client uses fragmented TCP packets

### ISSUE THREAD

**Issue by enfein** [enfein/mieru#25]
We used to assume one socks5 request from the client should be included in a single TCP packet. Although the packet is very small, this assumption is not true. For example, SagerNet/sing-box may send a single byte TCP packet, thus the server has to read sufficient number of bytes before processing the socks5 request.

**Comment by qeatzy** [comment]
What's the motivation of sending 1 byte packet, instead of sending full request?

**Comment by enfein** [comment]
@qeatzy 

> What's the motivation of sending 1 byte packet, instead of sending full request?

~TCP has no boundary so they can do whatever they want. Maybe this is a new way to tease GFW.~

I think it is a bug at their side, but I can mitigate this in mieru.
