### ISSUE TITLE
Sagernet mieru plugin error (libmieru exits too fast)

### ISSUE THREAD

**Issue by jose-C2OaWi** [enfein/mieru#27]
libmieru exits too fast (exit code:1)

Related log:
I/libmieru: 2022-08-32T25:67:74Z WARNING use stdout for logging due to the following error: prepareClientLogDir() failed: neither $XDG_CACHE_HOME nor $HOME are defined
I/libmieru: 2022-08-32T25:67:74Z FATAL load mieru client config failed: clientConfigFilePath() failed: prepareClientConfigDir() failed: neither $XDG_CONFIG_HOME nor $HOME are defined
D/v2ray-core: app/log: Logger closing

Sagernet Screenshot:
![Screenshot_Issue](https://user-images.githubusercontent.com/111356383/184872029-1b22ee6d-63b6-4598-81ef-6460d5c4c327.png)

**Comment by enfein** [comment]
You may ran into version mismatch.

What is your SagerNet and mieru plugin version?

Can you download SagerNet 0.8.1-rc02 and mieru plugin 1.6.1 from SagerNet GitHub release page and retry?

**Comment by jose-C2OaWi** [comment]
Thanks for help.
My mieru plugin was version 1.5.1 with SagerNet 0.8.1-rc02. Now I install mieru plugin 1.6.1 and it works fine.
