### ISSUE TITLE
服务端载入配置后，密码变成乱码

### ISSUE THREAD

**Issue by tdjnodj** [enfein/mieru#28]
系统:debian11
ssh软件:finalshell mac版
不管是用nano还是下载到本机查看配置文件，密码都是自己设定的，可在服务端输入`mita describe config`后，输出的配置文件里的密码确是乱码，再次检查服务端的配置文件，密码依然正常人。并且运行后客户端不管输入原密码还是乱码都无法连接。
![屏幕快照 2022-08-17 下午1 43 17](https://user-images.githubusercontent.com/108401163/185043893-82e0dd6f-3688-409f-8a35-8adec58ff484.png)
![屏幕快照 2022-08-17 下午1 43 28](https://user-images.githubusercontent.com/108401163/185043906-bd5fc016-5bfb-4540-847c-04360860fd82.png)

**Comment by enfein** [comment]
服务端只存储密码的哈希值。该值只要和 `mieru describe config` 的结果对应即可。
