### ISSUE TITLE
客户端可以提供service吗

### ISSUE THREAD

**Issue by 10ta** [enfein/mieru#30]
运行了一下午 因为 too many open files 停止了，所以问一下客户端考虑使用service吗

**Comment by enfein** [comment]
类似的问题，我在之前已经有过答复 https://github.com/enfein/mieru/issues/24#issuecomment-1197486611

这个 too many open files 可能是个 bug。你能提供更详细的描述么？例如系统中客户端打开的网络连接的数量，以及客户端日志信息

```
[metrics - connections] ActiveOpens=3 CurrEstablished=2 MaxConn=3 PassiveOpens=0
```

**Comment by 10ta** [comment]
为了节省性能，日志等级开了ERROR 当时只留下了这两句日志。接下来改为DEBUG尝试复现。
2022-09-06T16:10:16+08:00 ERROR encountered error when socks5 server accept new connection: accept tcp [::]:33333: accept4: too many open files
2022-09-06T16:10:16+08:00 FATAL run socks5 server failed: accept tcp [::]:33333: accept4: too many open files

**Comment by 10ta** [comment]
另外，尝试写systemd的service文件，尝试运行时报错：
```
Sep 07 23:32:00 xxx systemd[1]: Starting Mieru proxy server...
Sep 07 23:32:00 xxx systemd[1]: Started Mieru proxy server.
Sep 07 23:32:00 xxx mieru[70984]: 2022-09-07T23:32:00+08:00 WARNING use stdout for logging due to the following error: prepareClientLogDir() failed: neither $XDG_CACHE_HOME nor $HOME are defined
Sep 07 23:32:00 xxx mieru[70984]: 2022-09-07T23:32:00+08:00 FATAL load mieru client config failed: clientConfigFilePath() failed: prepareClientConfigDir() failed: neither $XDG_CONFIG_HOME nor $HOME are defined
Sep 07 23:32:00 xxx systemd[1]: mieru.service: Main process exited, code=exited, status=1/FAILURE
Sep 07 23:32:00 xxx systemd[1]: mieru.service: Failed with result 'exit-code'.
```

service文件用了mita的
```
[Unit]
Description=Mieru proxy server
After=network-online.target network.service networking.service NetworkManager.service systemd-networkd.service
Wants=network-online.target
StartLimitBurst=5
StartLimitIntervalSec=60

[Service]
Type=exec
ExecStart=/usr/bin/mieru run
Nice=-10
Restart=on-failure
RestartSec=1
LimitNOFILE=102400

[Install]
WantedBy=multi-user.target
```

**Comment by enfein** [comment]
个人猜测，too many open files 可能是因为很多 UDP connection 没有及时清理导致的。mieru 清理 UDP connection 比较懒惰。你的负载大量使用了 socks5 UDP association，因为这个功能暂时还没实现，会导致 connection 断掉，清理不及时就容易爆。如果只使用 TCP **代理协议**应该不会有这个问题。

```
UnsupportedCommand=770  <--- 这些都是 socks5 UDP association 导致的
```

关于 systemd mieru service，不知道为什么没有 `$HOME`。讲道理即便是 root 用户也会有 `$HOME` 环境变量。如果想绕开这个错误，除了设置 `$HOME` 之外，也可以加上下面的设置

```
...

[Service]
Environment=MIERU_CONFIG_JSON_FILE=/root/client_config.json
...
```

其中 `/root/client_config.json` 是教程中提及的用于 apply config 的 **JSON** 文件。使用 `$MIERU_CONFIG_JSON_FILE` 的时候，就不再需要 `mieru apply config` 了。

**Comment by enfein** [comment]
参考 https://github.com/enfein/mieru/blob/main/configs/examples/mieru.service

试了一下发现 systemd 确实没有设置 `$HOME`，在 shell 里用 root 用户运行则不会有这个问题。

**Comment by 10ta** [comment]
> 个人猜测，too many open files 可能是因为很多 UDP connection 没有及时清理导致的。mieru 清理 UDP connection 比较懒惰。你的负载大量使用了 socks5 UDP association，因为这个功能暂时还没实现，会导致 connection 断掉，清理不及时就容易爆。如果只使用 TCP **代理协议**应该不会有这个问题。
> 
> ```
> UnsupportedCommand=770  <--- 这些都是 socks5 UDP association 导致的
> ```
> 
> 关于 systemd mieru service，不知道为什么没有 `$HOME`。讲道理即便是 root 用户也会有 `$HOME` 环境变量。如果想绕开这个错误，除了设置 `$HOME` 之外，也可以加上下面的设置
> 
> ```
> ...
> 
> [Service]
> Environment=MIERU_CONFIG_JSON_FILE=/root/client_config.json
> ...
> ```
> 
> 其中 `/root/client_config.json` 是教程中提及的用于 apply config 的 **JSON** 文件。使用 `$MIERU_CONFIG_JSON_FILE` 的时候，就不再需要 `mieru apply config` 了。

我回忆了一下是的，当时我用了UDP模式，而ulimit open files = 1024 一段时间之后就超过了
今天一整天TCP模式没有再退出
接下来准备在service里给client加这么一条再试试UDP
LimitNOFILE=102400
感谢
