### ISSUE TITLE
支持端口区间简化配置

### ISSUE THREAD

**Issue by betteray** [enfein/mieru#32]
支持端口范围段好支持么，不然配置文件也太长了

**Comment by enfein** [comment]
什么时候需要监听很多个端口呢？开机场？

**Comment by betteray** [comment]
感谢回复，只是手写配置，写了10多个连续的端口，完了客户端也跟着一痛改，而且配置文件就是显的很长。

不开机场。

**Comment by danangua** [comment]
多端口可以自己在vps里转发实现？例如iptables

**Comment by betteray** [comment]
@danangua 有空学习一下 iptables ,还没实践用过

**Comment by enfein** [comment]
我在其他代理软件里面没有见到过类似的功能,看来这个功能需要的人不多,暂不打算支持.
