### ISSUE TITLE
Error exit to fast!

### ISSUE THREAD

**Issue by rootergod** [enfein/mieru#33]
I get this error (v2ray v4.45.2 server and mieru 1.7 and client is SageNet), any solution?
Both side use 1.7.0 mieru version
![Screenshot_20221010-210615_SagerNet](https://user-images.githubusercontent.com/7557929/194991044-a7512f7c-be23-49df-85e8-ba0002a146ba.png)
![Screenshot_20221010-210654_SagerNet](https://user-images.githubusercontent.com/7557929/194991063-bbfe51b6-d097-482b-be7c-2f81dc8d7295.png)

**Comment by enfein** [comment]
Please try SagerNet version 0.8.1-rc02, mieru plugin 1.7.0 and mita server 1.7.0. This SagerNet apk can be downloaded from GitHub release page.

**Comment by narakai** [comment]
Same issue here. 
SagerNet version 0.8.1-rc02, mieru-plugin-1.5.0
Mieru plugin 1.7.0 and mita server 1.7.0

**Comment by enfein** [comment]
Let me try the combination of SagerNet 0.8.1-rc02 + mieru plugin 1.7.0 + mita server 1.7.0.

**Comment by enfein** [comment]
@rootergod and @narakai 

Checked on my phone, if your configuration is correct, and you use SagerNet 0.8.1-rc02 + mieru plugin 1.7.0 downloaded from SagerNet release, you shouldn't have this error.

**Comment by narakai** [comment]
Double checked with mieru plugin 1.7.0, it works for me now.

**Comment by enfein** [comment]
I am closing this. @rootergod let me know if you still face this error.
