### ISSUE TITLE
Join Revolt Chat Room at https://rvlt.gg/kxEe3FQR

### ISSUE THREAD

**Issue by enfein** [enfein/mieru#39]
Based on discussions #38 I created a revolt chat room for mieru users.

Link: https://rvlt.gg/kxEe3FQR

I won't be online very often. Hope you enjoy chatting with other people.

**Comment by i39v** [comment]
出于安全考虑，个人建议开发者“enfein”这个虚拟身份包含的账号越少越好，在线时间和在线次数也越少越好。

**Comment by enfein** [comment]
@i39v 谢谢提醒。我是编程随想博客的老读者，对这些原理比较熟悉。要做好不同虚拟身份之间的隔离，以及虚拟身份活动与肉身活动的隔离。本项目不设立官方电报群，不在知名社交媒体上推广也是为了我自身的安全。

**Comment by i39v** [comment]
> @i39v 谢谢提醒。我是编程随想博客的老读者，对这些原理比较熟悉。要做好不同虚拟身份之间的隔离，以及虚拟身份活动与肉身活动的隔离。本项目不设立官方电报群，不在知名社交媒体上推广也是为了我自身的安全。

根据目前的消息，编程随想八成是被抓了，疑似是通过社会工程学找到真身的，开发者注意安全。
[Reddit 1](https://libreddit.nl/r/real_China_irl/comments/11xgyy5/%E7%96%91%E4%BC%BC%E7%BC%96%E7%A8%8B%E9%9A%8F%E6%83%B3%E5%AE%B6%E5%B1%9E%E5%8F%91%E5%A3%B0%E6%B1%82%E6%95%91/)
[Reddit 2](https://libreddit.nl/r/real_China_irl/comments/11xlx44/%E5%8E%BB%E5%B9%B4%E6%88%91%E5%AE%9A%E4%BD%8D%E5%88%B0%E7%BC%96%E7%A8%8B%E9%9A%8F%E6%83%B3%E7%9A%84%E8%BF%87%E7%A8%8B/)

**Comment by enfein** [comment]
@i39v 我的猜想是，编程随想早期注册的账号暴露了部分线索，使得中共可以逐一排查精通信息安全的人，最终锁定目标。

除了技术层面，我应对社工的办法是，强迫自己只在公开渠道上与其他人交流。Github issue 和 Revolt chat 的历史是所有人可见的，这让我每时每刻提醒自己尽量少暴露个人相关的信息。如果查找我的成本远大于收益，我就是安全的。
