### ISSUE TITLE
客服端是否支持多个servers？

### ISSUE THREAD

**Issue by yqk100** [enfein/mieru#41]
一个配置文件写入多个servers，支持吗？

**Comment by enfein** [comment]
支持，只要每个 server 上都配置了同一个用户就可以。

**Comment by a9k1n9** [comment]
不是很明白，有示例文档吗？

**Comment by enfein** [comment]
例如你有 `1.2.3.4` 和 `2.3.4.5` 两台服务器，分别监听 `2022` 和 `2027` 端口，且都配置了 `user1` 这个 mieru 用户，那么客户端配置文件可以这么写

```json
{
    "profiles": [
        {
            "profileName": "default",
            "user": {
                "name": "user1",
                "password": "pass"
            },
            "servers": [
                {
                    "ipAddress": "1.2.3.4",
                    "portBindings": [
                        {
                            "port": 2022,
                            "protocol": "TCP"
                        }
                    ]
                },
                {
                    "ipAddress": "2.3.4.5",
                    "portBindings": [
                        {
                            "port": 2027,
                            "protocol": "TCP"
                        }
                    ]
                }
            ],
            "mtu": 1400
        }
    ],
    "activeProfile": "default",
    "rpcPort": 8964,
    "socks5Port": 1080,
    "loggingLevel": "INFO"
}
```

**Comment by a9k1n9** [comment]
不能udp和tcp公用一个配置文件吗？
但是tcp、udp各开启一个mieru，在win端下开机自启大概率后面启动mieru无法使用～ 
socks5Port、rpcPort并不重复

**Comment by ayanami-desu** [comment]
> 例如你有 `1.2.3.4` 和 `2.3.4.5` 两台服务器，分别监听 `2022` 和 `2027` 端口，且都配置了 `user1` 这个 mieru 用户，那么客户端配置文件可以这么写
> 
> ```json
> {
>     "profiles": [
>         {
>             "profileName": "default",
>             "user": {
>                 "name": "user1",
>                 "password": "pass"
>             },
>             "servers": [
>                 {
>                     "ipAddress": "1.2.3.4",
>                     "portBindings": [
>                         {
>                             "port": 2022,
>                             "protocol": "TCP"
>                         }
>                     ]
>                 },
>                 {
>                     "ipAddress": "2.3.4.5",
>                     "portBindings": [
>                         {
>                             "port": 2027,
>                             "protocol": "TCP"
>                         }
>                     ]
>                 }
>             ],
>             "mtu": 1400
>         }
>     ],
>     "activeProfile": "default",
>     "rpcPort": 8964,
>     "socks5Port": 1080,
>     "loggingLevel": "INFO"
> }
> ```
> 

这样写的话，最终连接的是哪个服务器呢，还是说负载均衡？

**Comment by enfein** [comment]
> 在win客户端有办法一个走TCP一个走UDP下同时使用的配置文件示例吗？
> 一份配置文件中包含两个socks5本地端口，一个[1080]走TCP，一个[1081]走UDP这样子......

上面的例子，把一个 `portBindings` 中的 `protocol` 改成 UDP，另一个依旧维持 TCP，就可以了

**Comment by enfein** [comment]
> 这样写的话，最终连接的是哪个服务器呢，还是说负载均衡？

是负载均衡 @ayanami-desu

**Comment by molezz** [comment]
负载的，为什么我按照写了一个2服务器的，get connections显示始终用那个aa.com的各种端口， ip那个一直用不上

```
            "servers": [
                {
					"ipAddress": "1.2.3.4",
					"domainName": "",
                    "portBindings": [
                        {
                            "portRange": "1000-1100",
                            "protocol": "TCP"
                        }
                    ]
                },
                {
					"domainName": "aa.com",
                    "portBindings": [
                        {
                            "portRange": "1000-1100",
                            "protocol": "TCP"
                        }
                    ]
                }
            ],
            "mtu": 1400,
            "multiplexing": {
                "level": "MULTIPLEXING_MIDDLE"
            }
        }
```

**Comment by enfein** [comment]
@molezz 

建议打开客户端的调试日志，看看每个连接去了哪里，以及运行 `mieru get metrics` 看看是否连接有错误。`mieru get connections` 只显示还没有关闭的连接。

我猜测可能是 MULTIPLEXING_MIDDLE 会重用已有的物理连接导致的，可以使用 MULTIPLEXING_OFF 关掉多路复用再试试。

如果这些都试过但依旧只去一台服务器，应该是bug.

**Comment by molezz** [comment]
反复测试了下，不是只用domain，而是好像只用第二个server。
我将两个配置上下顺序换了下，domain放到json第一个，就变成只用ip那个了（后续server）
另外我又测试了同一server, 都用ip
上面一个v4 ip，下面一个v6 ip， 结果只连v6那个，哪怕当前只是v4网络，导致无法连接。v4，v6上下互换，既v4顺序第二客户端正常连接。

```
  "servers": [
                {
		    "ipAddress": "v4",
                    "portBindings": []
                 },
                {
                {
		    "ipAddress": "v6",
                    "portBindings": []
                 }
]
```



## get metrics

```
{
    "cipher - client": {
        "DirectDecrypt": 19365,
        "FailedDirectDecrypt": 0
    },
    "connections": {
        "ActiveOpens": 113,
        "CurrEstablished": 27,
        "MaxConn": 41,
        "PassiveOpens": 0
    },
    "HTTP proxy": {
        "ConnErrors": 0,
        "Requests": 0,
        "SchemeErrors": 0
    },
    "replay": {
        "KnownSession": 0,
        "NewSession": 0,
        "NewSessionDecrypted": 0
    },
    "socks5": {
        "ConnectionRefusedErrors": 0,
        "DNSResolveErrors": 0,
        "HandshakeErrors": 10,
        "HostUnreachableErrors": 0,
        "NetworkUnreachableErrors": 0,
        "UDPAssociateErrors": 0,
        "UnsupportedCommandErrors": 0
    },
    "socks5 UDP associate": {
        "DownloadBytes": 0,
        "DownloadPackets": 0,
        "UploadBytes": 0,
        "UploadPackets": 0
    },
    "traffic": {
        "DownloadBytes": 12684045,
        "OutputPaddingBytes": 376458,
        "UploadBytes": 1257560
    },
    "underlay": {
        "ActiveOpens": 113,
        "CurrEstablished": 39,
        "MaxConn": 53,
        "PassiveOpens": 0,
        "UnderlayMalformedUDP": 0,
        "UnsolicitedUDP": 0
    }
}
```

## info改成了debug, 多路off
```
            ],
            "mtu": 1400,
            "multiplexing": {
                "level": "MULTIPLEXING_OFF"
            }
        }
    ],
    "activeProfile": "default",
    "rpcPort": 8964,
    "socks5Port": 1080,
    "loggingLevel": "DEBUG",
    "socks5ListenLAN": false,
    "httpProxyPort": 1081,
    "httpProxyListenLAN": false
}
```

**Comment by enfein** [comment]
@molezz 应该是 v2.4.0 版本引入的 bug，这个问题在 v3.3.3 修复了。
