### ISSUE TITLE
能否支持docker运行？

### ISSUE THREAD

**Issue by ayanami-desu** [enfein/mieru#42]
我尝试了一晚上，最后得到的成果是容器运行之后立刻退出……
在配置中设置日志等级为TRACE也未见更多输出
Attaching to mieru
mieru  | mieru client is started, listening to 127.0.0.1:56464
mieru exited with code 0
mieru  | mieru client is started, listening to 127.0.0.1:56464
mieru exited with code 0
mieru  | mieru client is started, listening to 127.0.0.1:56464
mieru exited with code 0
mieru  | mieru client is started, listening to 127.0.0.1:56464
mieru exited with code 0

**Comment by ayanami-desu** [comment]
Entrypoint.sh原本只有一行
mieru start
我经过搜索之后，加上了一行
tail -f /dev/null
本来是想让容器不退出方便调试的，结果直接能用了。看来是启动命令的问题，请问有什么别的方法能解决吗？

**Comment by enfein** [comment]
首先我认为在容器里面运行客户端程序没有任何好处.

至于你的问题,你需要知道一点

> 如果容器的主进程退出了,容器的生命周期也就结束了.

假定 `Entrypoint.sh` 是容器的主进程,这里面的最后一个指令是 `mieru start`. `mieru start` 做的事情是在后台运行 `mieru run` 并退出.它退出之后容器的生命周期就结束了,那个刚刚创建的后台进程 `mieru run` 也会一起死掉,所以你在日志里面什么都看不到.想要修复这个问题,如果你在容器的 `Entrypoint.sh` 里面使用 `mieru apply config ...` 正确配置了客户端,只要把最后一个指令改成 `mieru run` 即可.

**Comment by ayanami-desu** [comment]
感谢解答，至于我为什么要用docker运行客户端，是因为我想要在软路由上运行mieru，通过passwall等软件转发socks到客户端

**Comment by enfein** [comment]
你用的软路由只能运行容器不能直接运行一个二进制程序么?

**Comment by ayanami-desu** [comment]
系统是openwrt，aarch64架构的，release中有这个架构的客户端，但我没有找到这个系统如何进行rpm安装。

**Comment by enfein** [comment]
客户端只有一个二进制文件，因此不一定需要 deb 或者 rpm 安装包。你可以下载

```
https://github.com/enfein/mieru/releases/download/v1.8.1/mieru_1.8.1_linux_arm64.tar.gz
```

然后解压缩即可。

**Comment by ayanami-desu** [comment]
aarch64架构的客户端并没有tar.gz压缩包
但我发现rpm也是可以解压的。能否考虑以后只release二进制文件呢

**Comment by enfein** [comment]
处理器的架构有不同的名字，Redhat 叫 `x86_64` 和 `aarch64`，Debian 叫 `amd64` 和 `arm64`。其实他们是一回事。那个 `mieru_1.8.1_linux_arm64.tar.gz` 应该可以在你的软路由里面运行。

**Comment by ayanami-desu** [comment]
确实可以运行
非常感谢！
