### ISSUE TITLE
客户端如何分别独立运行多个配置？

### ISSUE THREAD

**Issue by re-move** [enfein/mieru#43]
首先感谢 @enfein ，当前流行依赖web服务器伪装和CDN的技术路线实在违背我的常识。

如题，在某些场景下，需要单独使用指定服务器的线路，而不是无法选择服务器的负载均衡，这就需要每个服务器各自独立配置，以实现任意切换指定的服务器，或者独立运行多个客户端和配置来实现 (×_×)

我主要在Windows环境下使用，已经尝试了多种方法都无法达成这个目的，请问有实现方案吗？

谢谢

**Comment by enfein** [comment]
有两种办法。

第一，如果同一时间，你的所有应用程序只需要连接某一台服务器，这可以用客户端自带的 profile 功能。因为这是一个比较高级的功能，在教程里面没有提及。一个参考配置如下

```json
{
    "profiles": [
        {
            "profileName": "server1",
            "user": {
                "name": "user1",
                "password": "pass1"
            },
            "servers": [
                {
                    "ipAddress": "1.1.1.1",
                    "portBindings": [
                        {
                            "port": 1111,
                            "protocol": "TCP"
                        }
                    ]
                }
            ],
        },
        {
            "profileName": "server2",
            "user": {
                "name": "user2",
                "password": "pass2"
            },
            "servers": [
                {
                    "ipAddress": "2.2.2.2",
                    "portBindings": [
                        {
                            "port": 2222,
                            "protocol": "TCP"
                        }
                    ]
                }
            ],
        }
    ],
    "activeProfile": "server1",
    "rpcPort": 3333,
    "socks5Port": 4444,
    "loggingLevel": "INFO"
}
```

现在客户端会连接 server1，如果想要切到 server2，应用下面的设置并重启客户端即可。

```json
{
    "activeProfile": "server2"
}
```

第二，如果不同的应用程序必须同时连接不同的指定服务器，这时候你必须开启多个 mieru 客户端。这件事稍微复杂一些。首先你需要准备两个不同的客户端配置文件，他们要使用不同的 `rpcPort` 和 `socks5Port`，然后配置环境变量 `MIERU_CONFIG_JSON_FILE` 分别指向两个配置文件的同时使用 `mieru run` 运行两个客户端程序。我不太清楚在 Windows 系统下怎么指定环境变量和文件路径，所以就不贴示例了。

**Comment by re-move** [comment]
谢谢及时解答，看来 @enfein 对 Windows 用户还没来得及赋予足够同情  -_-"

方法一前几天实现过，但每次手写改配置再重启…… 

方法二正是我想达到的目的，看到你的回复后尝试了多种环境变量的格式，都提示 `D :: The filename, directory name, or volume label syntax is incorrect.` （mieru.exe放在D盘）。

试过的变量值格式：
格式1，形如：`D:\config1.json;D:\config2.json`
格式2，形如：`r'D:\config1.json';r'D:\config2.json'`
格式3：`D:\\config1.json;D:\\config2.json`
格式4：`\\?\D:\config1.json;\\?\D:\config2.json`
格式5：自定义一个新环境变量MIERU2，值为 `D:\config2.json` ，`MIERU_CONFIG_JSON_FILE` 的值设为 `D:\config1.json;%MIERU2%`
格式6：以上方法的搭配组合

临近崩溃的时候，我放弃了  (╯°□°）╯︵ ┻━┻

**Comment by enfein** [comment]
如果方案 1 可行，应该没有想象中那么麻烦。你需要准备 config1.json 和 config2.json。它们只有 `activeProfile` 那一行不一样，需要换的时候重新 `mieru apply config ... && mieru stop && mieru start`。

方案 2 这里我只能介绍一下 Linux 的做法，可以参照 https://github.com/enfein/mieru/blob/main/configs/examples/mieru.service 准备 mieru1.service 和 mieru2.service，里面分别指定 `MIERU_CONFIG_JSON_FILE=/etc/mieru_client_config1.json` 和 `MIERU_CONFIG_JSON_FILE=/etc/mieru_client_config2.json`。这样就可以同时运行两个客户端了。

没办法我不懂 windows 上怎么搞。

**Comment by enfein** [comment]
试出来了。

开两个命令提示符窗口，指令分别是 `cmd /V /C "set MIERU_CONFIG_JSON_FILE=C:\config1.json&& mieru run"` 和 `cmd /V /C "set MIERU_CONFIG_JSON_FILE=C:\config2.json&& mieru run"`。

注意文件路径不能有空格，`json` 和 `&&` 之间也不能有空格。

参考 https://superuser.com/questions/223104/setting-and-using-variable-within-same-command-line-in-windows-cmd-exe

**Comment by enfein** [comment]
> 摆脱命令行窗口保持后台进程

这也是 windows 特有的问题，我还不知道怎么解决。

**Comment by re-move** [comment]
@enfein 按你的方法成功了

你不熟悉 Windows ，我不是程序猿，用笨办法摆脱命令行窗口，提供给其它和我一样的小伙伴吧——

建立1.bat
`@echo off
if "%1" == "h" goto begin 
mshta vbscript:createobject("wscript.shell").run("%~nx0 h",0)(window.close)&&exit 
:begin
set MIERU_CONFIG_JSON_FILE=D:\Mieru\client1.json&& mieru run`

建立2.bat
……

查看端口：
`netstat -ano | findstr 12345`

**Comment by re-move** [comment]
看[issues](https://github.com/enfein/mieru/issues/87)有人提到了vbs即将寿终的问题，我早换了[winsw](https://github.com/winsw/winsw) 方式，只是因为自己太业余就没发到这里来。下面还是提供和我相似水平的Windows用户参考：

通过winsw将mieru安装为系统服务，开机运行

下载https://github.com/winsw/winsw/releases
WinSW-x64.exe与WinSW-x86.exe无系统依赖，可运行在没有安装.net环境的windows电脑中，但文件体积较大。
WinSW.NET2.exe、WinSW.NET4.exe、WinSW.NET461.exe需要运行在安装了.net包的运行环境中，但是文件较小。

配置文件.xml似乎应为 UTF-8 编码：
```
<service>
  <id>Mieru_X1</id>
  <name>_Mieru_X1</name>
  <description>Mieru X1.</description>
  <env name="MIERU_CONFIG_JSON_FILE" value="D:\Proxy\Mieru\X1.json"/>
  <executable>D:\Proxy\Mieru\mieru.exe</executable>
  <delayedAutoStart>true</delayedAutoStart>
  <startarguments>run</startarguments>
  <stoparguments>stop</stoparguments>
  <log mode="none"></log>
</service>
```
命令行执行：
安装：winsw install D:\Proxy\Mieru\X1.xml
启动：winsw start D:\Proxy\Mieru\X1.xml
查看：winsw status D:\Proxy\Mieru\X1.xml
