### ISSUE TITLE
How is this any different than Shadowsocks?

### ISSUE THREAD

**Issue by 0xNeu** [enfein/mieru#45]
Hi,
I went through the README and I'm wondering how is this any different than existing solutions such as Shadowsocks (aside from UDP support which is a big plus)?

**Comment by enfein** [comment]
Hi Lem0nade,

_Let me answer this question from only protocol's view. I am not going to talk about feature set and implementation._

This depends on which shadowsocks you are talking about.

For the original shadowsocks and shadowsocksR, some flaws in their protocols are revealed over the years, causing active probing and disruption. You should not use shadowsocks and shadowsocksR anymore.

mieru learned the lessons from those failures and designed the protocol to fix those issues.

shadowsocks 2022 was independently developed at the same time frame as mieru, to replace shadowsocks and shadowsocksR. mieru is a good alternative to shadowsocks 2022 given it is less well known and thus not making sense for censorship to target specifically, at the moment.
