### ISSUE TITLE
TCP mode not work?

### ISSUE THREAD

**Issue by italy2010** [enfein/mieru#46]
Hello i tested mita 
udp mode with unbloked internet work.
but tcp mode with blocked and unblocked internet not working!.

**Comment by enfein** [comment]
Hi italy2010,

Please take a look at https://github.com/enfein/mieru/blob/main/docs/operation.md to see troubleshooting guidance.

If you need help, at lease provide the following information:

1. what you did and what you saw
2. version of server and client
3. server and client configuration, remove sensitive information
4. server and client logs
