### ISSUE TITLE
Mieru運行後在Windows上socks5無法使用

### ISSUE THREAD

**Issue by yatounoneko** [enfein/mieru#49]
### 無法在windows上使用mieru
	配置能夠正常使用，運行後也提示正常。
	使用socks5(SwitchyOmega/Netch)連接後無法正常運作。
	TCPING測試正常
	SagerNet能夠正常使用，無論TCP還是UDP

![](https://oxo.hk/index.php?explorer/share/file&hash=88c6FZHqS2fuNvCLV_vTi9U7hasouitfl3zeH82DXvRoIy22BBlI-afkLfojEvxrtrzeCA)
![](https://oxo.hk/index.php?explorer/share/file&hash=f943aAdLrcsmNsgwqOUe1oyOlr8Kr-uR3Pxo0kDGw57VmqQR4kOIj5BylVWiXgyGJrwiJw)
![](https://oxo.hk/index.php?explorer/share/file&hash=c875JG1XOz0Wf_DEiG5rl_KKIYjDecChBZc3Up1OzWGPW3i-rKE9HgzkSb1uPdtfdjNS1g)
![](https://oxo.hk/index.php?explorer/share/file&hash=29edoRokDBLeccZ5zNmWRWqO7WLHk-Rj4IJpG5Rele8kBrcaLE1jTpMwtKrWddfZ6PRgSg)
![](https://oxo.hk/index.php?explorer/share/file&hash=79be_p1hZetg8zdSbWldHrJOL1RG3w7KC_-mcm_fqR3aaYXy_p-Up3euihmrp_Kl-j4OLQ)
![](https://oxo.hk/index.php?explorer/share/file&hash=2c64i3JFkOWElc1h-3uYVQQSagOzbZX_vzdA9CFEtdQWguc0L6SGW9HPTCxGCnnGKRui1A)

**Comment by enfein** [comment]
能够提供客户端和服务器的日志？调试日志记得脱敏。查看日志的方法请见 https://github.com/enfein/mieru/blob/main/docs/operation.zh_CN.md

**Comment by yatounoneko** [comment]
問題找到了（原來mieru的機器時間差了一個小時，現在好了:)
---
### Mieru：
    2023-01-24T17:56:31+08:00 INFO mieru client RPC server is running
    2023-01-24T17:56:31+08:00 INFO UDP session MTU is set to 1400
    2023-01-24T17:56:31+08:00 INFO mieru client socks5 server is running
    2023-01-24T17:56:31+08:00 INFO enabled metrics logging with duration 1m0s
    2023-01-24T17:56:31+08:00 INFO return app status RUNNING back to RPC caller
    2023-01-24T17:56:35+08:00 INFO return app status RUNNING back to RPC caller
    ......
### Mita:
    Jan 24 18:56:14 WFG mita[529]: INFO return app status IDLE back to RPC caller
    Jan 24 18:56:14 WFG mita[529]: INFO received start request from RPC caller
    Jan 24 18:56:14 WFG mita[529]: INFO UDP session MTU is set to 1400
    Jan 24 18:56:14 WFG mita[529]: INFO mieru server daemon socks5 server "[::]:2027" is running
    Jan 24 18:56:14 WFG mita[529]: INFO mieru server daemon socks5 server "[::]:2012" is running
    Jan 24 18:56:14 WFG mita[529]: INFO completed start request from RPC caller
    Jan 24 18:56:17 WFG mita[529]: INFO return app status RUNNING back to RPC caller
    ......
