### ISSUE TITLE
UDP頻繁發生阻斷現象

### ISSUE THREAD

**Issue by yatounoneko** [enfein/mieru#50]
近三天用下來發現udp協議反應很快，未出現反應緩慢或無響應。但經常會出現端口阻斷，然後換一個端口隨即恢復正常。
阻斷基本是在瀏覽視頻時發生，阻斷時速率不超過5Mbps。

tcp協議反應較為緩慢，似乎與網絡擁塞有關。效果是經常出現加載慢或無響應一段時間後又恢復正常。但tcp從未出現阻斷現象。

這種情況會不會是udp發送大量包而導致阻斷？
（是否考慮服務端監聽端口段來讓客戶端隨機使用，當一個端口失去響應或被阻斷後由客戶端嘗試選擇段內其他端口？）

**Comment by enfein** [comment]
谢谢你的反馈！我个人使用 UDP 没有遇到过阻断情况。如果能分享脱敏的客户端和服务器**调试**日志，我们可以尝试分析出现了什么问题。

UDP 比 TCP 反应更快是 UDP 使用了更激进的拥塞控制算法。如果你的网络有针对 UDP flood 限速那么这可能是阻断发生的原因。一种可能的解决办法是，配置多个监听端口，让每个连接走不同的端口。如果有多台服务器效果更好。

**Comment by yatounoneko** [comment]
似乎只能打印今天到11點開始的數據，但阻斷應該發生在凌晨，所以看不到阻斷的時候發生了什麽。
下載東西時好好的今天早上一看又無法使用了。

mieru的話阻斷時候是在用sagernet，似乎看不到日志。
剛才嘗試了用windows執行mieruUDP的連接，目前已被阻斷。
![image](https://user-images.githubusercontent.com/22129910/215013651-52e682d1-46fe-46cd-af7c-71b554ee9751.png)

進行了臨時測試阻斷端口，已將TCP與UDP改爲同一個端口，TCPing正常但UDP無法使用
測試環境：
Mieru - Windows11
Mita - Debian 11 (Hyper-V)

附上臨時測試日志：
[Mieru 測試日志文件(Debug)](#)
[Mita 測試日志文件(Debug)](#)

**Comment by enfein** [comment]
13:17:00 之后，客户端一共发送了 12 个创建连接的请求。我们逐一看一下。

## 55478

13:17:00 客户端创建，13:16:59 服务器收到，13:17:10 客户端关闭。原因：十秒钟之内未收到服务器的响应。

## 58191 58192 61728 61729 65470

同 55478 未收到服务器响应。

## 64577

客户端收到了 socks4 的请求，在客户端报错了。

## 61733

13:17:11 客户端创建，13:17:10 服务器收到，没有问题。

## 61058 56719

同 64577 属于不支持的 socks4 请求。不一样的是，服务器没有收到这两个连接的数据包。56719 可能是因为日志被砍掉了，不过 61058 肯定丢了。

## 56227 61265

同 61733，没有问题。

## 结论

我不太清楚这个服务器进程运行了多长时间，不过有两个地方很值得注意。

```
[metrics - cipher - server] FailedIterateDecrypt=10475
[metrics - replay] KnownSession=1 NewSession=15
```

第一点 `FailedIterateDecrypt` 表示其他人尝试向服务器发送信息，但是由于不知道密钥，无法被解密。这个数字正常情况下不会增长很快。以我在某 VPS 的情况来看，这个数字通常每天会增长几十。巨大的数字意味着有很多访问的尝试。

第二点，更重要的，我们看到有 1 个对旧链接的重放攻击，以及 15 个对新链接第一个数据包的重放攻击。如果是因为网络的原因导致出现重复的数据包，旧链接的重放攻击数应该远大于新链接。出现现在的情况只可能有一个原因，就是 GFW 在针对性地做主动探测。

非常感谢你提供了 mieru 被 GFW 主动探测的第一手信息。我原本以为 UDP 会更容易存活，但实际情况是 KCP 协议在某个时间尺度上的统计特性还是太明显了，恐怕已经被机器学习以一定的概率推算出来。我想之后可以在你的帮助下做几个实验，进一步了解 GFW 探测使用的特征。

缓解 UDP 主动探测的方法：让服务器多监听几个端口，客户端会做负载均衡，让一个端口的流量不至于过大。多开几台服务器效果更好。

**Comment by qeatzy** [comment]
还有一些是bots，我昨天在服务器上，有一个ip两个半小时auth read error 10334次。
同时类似的在国内的服务器上也遇到过之前3分钟500次连接。

平时也会有其他的访问的，但基本有以下特点。
- 频次不高
- 有不同的特点，有些只读，有些会写。我采用ecdh,看到大部分(>99%)是auth read error，少数是auth no pubkey，极少量是write error。
- 主动探测的话，不管是cracker，还是其他，几乎不可能全是auth read error。

用nmap探测了下10334次的连接，
135/tcp  filtered msrpc
139/tcp  filtered netbios-ssn
445/tcp  filtered microsoft-ds
593/tcp  filtered http-rpc-epmap
3389/tcp open     ms-wbt-server
4444/tcp filtered krb524

还有一些是isp/省际的问题。
前几天偶尔断的厉害，用winmtr测了下，第3跳路由40-60%丢包。

有几个问题。
- ssh访问会不会成为特征，是否已经/尚未被加入到决策的输入数据中。
- 手机端是否会有客户端受委托请求特点ip/domain，并上报。
- 从两方的角度，时序信息，都是很重要的点。
- kcp应该类似wireguard一样，特征明显，一个为安全加密，一个为克服恶劣网络。
- ecdh并不重。worker pool + batch pre-compute, 可以支持很高的新建连接速度。

**Comment by yatounoneko** [comment]
> 缓解 UDP 主动探测的方法：让服务器多监听几个端口，客户端会做负载均衡，让一个端口的流量不至于过大。多开几台服务器效果更好。

我會嘗試一下的，謝謝。
同時我也嘗試下在服務器硬件層的防火墻內用IP限制訪問看看有沒有改善，假如特性是主動探測的話。
但SagerNet目前還不支持mieru的多端口負載均衡，這個手機端可能就沒法解決了。

>我们看到有 1 个对旧链接的重放攻击，以及 15 个对新链接第一个数据包的重放攻击。

不知道是否與我開啟服務之後進行TCPing測試有關... 這個記錄我僅在TCPing測試通過後進行網頁訪問。
客戶端僅僅配置了UDP，但服務端配置了TCP以便我測試線路是否能通。
~~*但結合我這幾年使用多種KCP反向梯子的結果來看，速度是快，但封的也快:(*~~

---
另外想提一下，我發現如果透過mieru傳輸同一條線路的情況下，使用SSL的V走內網mieru能去到1-2M/s。
（當然因為眾所周知的原因，很快就會掛掉了，和mieru無關。）

但如果mieru直連，無論是TCP或UDP模式速率都會被限制在150-400K/s左右，速度與Zeroiter類似。
套上Zeroiter我也試過，但速度並沒有什麼改善。

Zeroiter與mieru傳輸的速率似乎互不影響，同時進行傳輸的話同一個服務器的速率能高過上述速率。
不清楚是不是與墻有關，但可能是以端口來限制速率，如果能透過多端口同時傳輸的話，會不會提高速率？~~(臆想x)~~

當然如果影響到解除封鎖的目的，那速率相對來說就並不是這麼重要了。

**Comment by enfein** [comment]
mieru 在 TCP 模式下的额外开销挺小的，基本上只有 AES 256 加解密。如果速度有明显降低，大概率是由于丢包触发拥塞控制算法限速导致的。开多个连接应该会有帮助。

**Comment by enfein** [comment]
现在看来非常有必要把 KCP 换掉。我去研究一下隔壁的 QUIC 是怎么做 ARQ 的。

**Comment by yatounoneko** [comment]
> 开多个连接应该会有帮助

測試了一段時間，負載均衡似乎並不會處理流量的速率。速率依舊維持在單個端口的限速上。

> 在服務器硬件層的防火墻內用IP限制訪問

好消息是，這個方法確實有用。目前透過指定IP訪問UDP端口，暫時沒有被封鎖的跡象。

**Comment by yatounoneko** [comment]
[](https://gfw.report/publications/usenixsecurity23/zh/)

FYI

**Comment by enfein** [comment]
@yatounoneko 

Thank you for sharing this! I made a quick fix in 1.14.0 version.
