### ISSUE TITLE
请问是否考虑增加redir功能？

### ISSUE THREAD

**Issue by eroica-zhao** [enfein/mieru#51]
我主要需求用于openwrt上，但目前好像不支持redir模式吧？
ss和trojan基本很难用了，用了几个月的naive，但是很奇怪在我的op上经常会断流，过几天就得重启进程，一直无解。
sagernet安卓端可以使用，比naive速度稍慢。但感觉挺稳定，想在op上用。
没有技术，只能做个伸手党，感谢作者！

**Comment by ayanami-desu** [comment]
openwrt不是可以直接运行二进制吗

**Comment by eroica-zhao** [comment]
> openwrt不是可以直接运行二进制吗

是可以运行，但目前只支持socks5，http吧？
没有办法在op上做透明代理，并基于防火墙规则做国内外分流。

**Comment by ayanami-desu** [comment]
你配合passwall，openclash, ssr plus之类的软件不就好了

**Comment by eroica-zhao** [comment]
> 你配合passwall，openclash, ssr plus之类的软件不就好了

哦哦，op端没用过这些，软路由固件都是自己从官方编译的，极简。
ss，trojan，naive都是基于redir，配合iptables自定义规则来用。
一语点醒，看来是我习惯了伸手要。
如果未来不准备支持，看来也只有这个办法了。

**Comment by yatounoneko** [comment]
雖然不清楚作者的態度，但作爲使用者，在我的認知裏mieru目前的核心功能僅爲實現突破網絡封鎖。
socks5和[v1.11.0](https://github.com/enfein/mieru/releases/tag/v1.11.0)後支持的HTTP代理，僅僅是爲了讓給系統或其他代理程式建立一個橋樑罷了。

以我的理解，實現代理或路由規則的功能看起來並不是mieru的主要目的。

> 没有办法在op上转发流量做透明代理，并基于防火墙规则做国内外分流。

你可以透過socks5代理程式或各OS可能自帶的HTTP代理協議連接，然後進行路由或規則定製。
SagerNet是個很好的例子，mieru僅僅作爲該程式中衆多插件之一。
因此所有的路由規則都基於SagerNet的核心運行和mieru沒有半毛錢關係，詳情可以瀏覽[「翻牆安全指南」](https://github.com/enfein/mieru/blob/main/docs/security.zh_CN.md)
> mieru 本身没有提供基于域名规则或 IP 地址位置来判断是否应该翻墙的功能。用户应当使用可以进行相关配置的浏览器插件，例如 [Proxy SwitchyOmega](https://github.com/FelisCatus/SwitchyOmega)，或者使用两个不同的浏览器，一个专门用于访问国内网站，而另一个专门用于翻墙。

至於其他流量代理和定義規則之類，還是留給想折騰GUI客戶端的人們去實現吧。

---
不過有一說一，mieru給的命令功能實在是太簡潔了，以至於其目的僅作用於應用配置、校對配置和開啓、關閉連接的功能...
想要弄自動化一鍵啓動或更換配置都是一件麻煩的事情: ( 
還得用cmd /k 又或是screen來保持常駐什麼的 )

「技術壁壘不利於傳火，但感覺對mieru來說卻是件好事」

**Comment by eroica-zhao** [comment]
谢谢您的回复。我明白作者的开发理念和出发点，所以只是询问，并没有要求，因为我明白自己只是一个伸手党，而作者纯粹基于自由共享的理念在做，我不能也不会做过多要求。
这几天搜了好多，没找到合适能用的openwrt端简洁轻量的透明代理软件（socks5,http），passwall openclash之类大而全的东西，作为一个精神洁癖者，真心不愿尝试（我承认，是我的问题）。

我花了好几天时间学习nftables，终于能通过规则实现自己需要的分流路由功能了（的确，meiru并无必要做这些）。
在我的使用环境里，naive速度最快，但在我第一个帖子里也说了，运行几个小时后会不明原因断流（作者库里面也有其他用户的类似issue提交，但作者似乎也无法锁定原因并解决）。
于是我找了redsocks，发现作者已经不再维护，而老版不支持nftables（有commit提交，但作者一直没有merge）。
另外一款hev socks5 proxy，只要运行就会导致多个log进程的cpu占用飙升，luci界面都停止响应。。。
哈哈，我只能歇了，再等有精力的时候找合适的吧。

sagernet我也在手机端使用，naive和mieru都可以顺畅使用（这也是naive在op上断流让人疑惑和头疼的地方）。
其实手机+pc都可以单独设置代理搞定，但家里有一些google的智能设备，需要路由器端的透明代理，折腾。。。

**Comment by yatounoneko** [comment]
也許你可以試試haproxy

> 简洁轻量单一功能的透明代理软件

**Comment by enfein** [comment]
谢谢几位的讨论。

我还没有搞过 OpenWRT 因此不能分享有用的经验。没研究 OpenWRT 的主要原因是，我作为开发者对安全的需求很高，只在单独的物理机器里面翻墙，其他的机器都是不翻墙的。

关于 GeoIP 域名规则这些，目前不打算做，原因有两个。第一我比较信奉 UNIX 哲学，一个软件做好一件事，额外的功能交给其他软件做，大家串起来就好。第二是提供这些复杂的配置工具需要很多精力，我做开发的时间有限，通过提交记录应该也能看出来。这时，把时间分配到最有价值的事情上，也就是突破封锁，是最好的选择。宁愿开发 V2 版本的协议对抗封锁，也不会给程序写一个 UI 让它更容易上手。

我做这个项目不是为了挣钱。能够在自己用的同时帮助一些人，已经很好了。如果突破封锁的能力得到了时间的检验，有人愿意拿去做成服务卖钱，或者愿意改进它变得更好用，我不胜感激。
