### ISSUE TITLE
Windows环境下怎么用？

### ISSUE THREAD

**Issue by DescentData** [enfein/mieru#55]
作者您好！请问mieru的windows客户端如何使用？下载下来的mieru.exe打开后就闪退，不知道应该如何运行？谢谢！

**Comment by enfein** [comment]
使用 cmd 或 PowerShell 或 Windows Terminal 输入命令。具体的命令见 https://github.com/enfein/mieru/blob/main/docs/client-install.zh_CN.md

mieru.exe 不是窗口程序无法通过双击打开进行操作。

**Comment by lm1618** [comment]
可以使用MatsuriDayo/nekoray 的自定义内核功能
