### ISSUE TITLE
TCP not work, UDP works but very unreliable!

### ISSUE THREAD

**Issue by essoojay** [enfein/mieru#56]
Internet = Yes
Mita version = 1.11.0 (compiled)
Android Client = Sagernet (Mieru Plugin 1.12.0 Latest)
Network = UDP and TCP

Complaint:
TCP = No internet at all  (even with working direct internet)
UDP = Sometimes it works for some seconds (most time not working)

INFO:
Feb 18 12:40:02 xx mita[775]: INFO [metrics]
Feb 18 12:40:02 xx mita[775]: INFO [metrics - cipher - server] DirectDecrypt=7 FailedDirectDecrypt=0 FailedIterateD>
Feb 18 12:40:02 xx mita[775]: INFO [metrics - connections] ActiveOpens=0 CurrEstablished=0 MaxConn=2 PassiveOpens=2
Feb 18 12:40:02 xx mita[775]: INFO [metrics - errors] KCPInErrors=0 KCPReceiveErrors=0 KCPSendErrors=0 TCPReceiveEr>
Feb 18 12:40:02 xx mita[775]: INFO [metrics - KCP] BytesReceived=281 BytesSent=4824 FastRetransSegs=0 InSegs=10 Los>
Feb 18 12:40:02 xx mita[775]: INFO [metrics - replay] KnownSession=0 NewSession=0
Feb 18 12:40:02 xx mita[775]: INFO [metrics - socks5] ConnectionRefusedErrors=0 DNSResolveErrors=0 HandshakeErrors=>
Feb 18 12:40:02 xx mita[775]: INFO [metrics - socks5 UDP associate] InBytes=0 InPkts=0 OutBytes=0 OutPkts=0
Feb 18 12:40:02 xx mita[775]: INFO [metrics - traffic] InBytes=1225 OutBytes=80754 OutPaddingBytes=3954
Feb 18 12:40:02 xx mita[775]: INFO [metrics - user - xxxxx] InBytes=1225 OutBytes=80754

Please what could be wrong?

**Comment by enfein** [comment]
The main difference between SagerNet and using mieru in PC is SagerNet has its own DNS solution. If it is not functional or very slow from the very beginning, it is likely that the DNS has some problem. Try using mieru in PC and see if it works. If PC is fine, then there is no problem at the server side, you need to configure DNS in SagerNet properly to protect the connection.

**Comment by NightMachinery** [comment]
> The main difference between SagerNet and using mieru in PC is SagerNet has its own DNS solution. If it is not functional or very slow from the very beginning, it is likely that the DNS has some problem. Try using mieru in PC and see if it works. If PC is fine, then there is no problem at the server side, you need to configure DNS in SagerNet properly to protect the connection.

I have set SagerNet to use `1.1.1.1` DNS. It still doesn't work at all (TCP or UDP). It works fine on PC. Any ideas?

Where are the server logs stored?

**Comment by enfein** [comment]
@NightMachinery 

The SagerNet v2ray core is outdated and DNS over TLS / DNS over HTTPS may not work.

https://github.com/enfein/mieru/blob/main/docs/operation.md talks about viewing logs.
