### ISSUE TITLE
Mac rpc didn't work

### ISSUE THREAD

**Issue by Grey0520** [enfein/mieru#57]
I meet
`mieru client is not running: ClientLifecycleService.GetStatus() failed: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp [::1]:8964: connect: connection refused"`

Env:

+ mac mini 2020 (arm)
+ download the file from release ` mieru_1.12.0_darwin_arm64.tar.gz ` and copy it to the /usr/local/bin

**Comment by enfein** [comment]
Did you run `mieru start` before `mieru status`?

If mieru is not started, in https://github.com/enfein/mieru/blob/8927a932c9b12215b372578ec111247272b83235/pkg/cli/client.go#L447 it is suppose to print "mieru client is not running". Somehow this logic is not working in your machine, so you get a detailed error message. This message is not a real error if mieru is not started.

**Comment by Grey0520** [comment]
I'm sorry I didn't describe the problem clearly.

I had this problem after I input the `mieru start`.

Here are some details about grpc: 
1388 is the rpc port in the config file
<img width="1551" alt="image" src="https://user-images.githubusercontent.com/70519059/227149956-e73d2b28-f63d-4e49-88f2-a9ffc70d5394.png">

**Comment by newmacuser** [comment]
Same issue is here with an OpenWRT system, using mieru 1.14.0.

After mieru start, it returns: 
mieru client is not running: ClientLifecycleService.GetStatus() failed: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp [::1]:10079: connect: connection refused"

Does the mieru client require some dependency on a concise Linux system like OpenWRT?

**Comment by enfein** [comment]
@newmacuser It should work on all Linux system.

If the error message you got was returned when you ran the `mieru start` command, it is possible that your system is slow, and we need a bigger time out.

If `mieru start` is successful, but you got error message later with `mieru status`, do you mind check the root cause with https://github.com/enfein/mieru/issues/57#issuecomment-1483567019?

**Comment by enfein** [comment]
Release v1.14.1 may help to resolve this issue.

**Comment by newmacuser** [comment]
Thank you for the prompt update of the software. The version 1.14.1 has solved this problem and made it work seamlessly on my OpenWRT system.

**Comment by Grey0520** [comment]
I will check it tomorrow.
And thank you.
