### ISSUE TITLE
[Q] Is there an iOS client?

### ISSUE THREAD

**Issue by NightMachinery** [enfein/mieru#58]

**Comment by enfein** [comment]
No we don't have one.

In general there is little motivation to develop open source iOS app because Apple doesn't allow side load. Users can't just compile from source code and install on their devices.

**Comment by samho1234567** [comment]
I suggest that the author build ipa file and let users sideload the app by Trollstore or AltStore.

**Comment by NightMachinery** [comment]
Shadowrocket is a one-time purchase app which is pretty good. Perhaps you can contact him to add this protocol to his app.

**Comment by samho1234567** [comment]
I reached out to the author of Shadowrocket, but he refuses to support Mieru at this moment.

**Comment by enfein** [comment]
Building a solid protocol remains the top priority of the project. UI, mobile app, ease of use can easily catch up once the quality of protocol is proven to be solid.

**Comment by SxierMe** [comment]
> I reached out to the author of Shadowrocket, but he refuses to support Mieru at this moment.

So, can you tell me why he refused to support it? thx

**Comment by samho1234567** [comment]
> > I reached out to the author of Shadowrocket, but he refuses to support Mieru at this moment.
> 
> So, can you tell me why he refused to support it? thx

The author just simply replied that he wouldn't support it at this moment without providing reasons on his blog. (conversions are written in Chinese)

https://liguangming.com/Shadowrocket#comment-6042688965

**Comment by enfein** [comment]
GPL-3 license might be an issue.

**Comment by msh-8** [comment]
is there any other way, except shodowrocket?

**Comment by yatounoneko** [comment]
> is there any other way, except shodowrocket?

Use Socks5 connection, you can setup the winodws client and open service port on windows firewall. Pass to iOS Socks5 proxy to connect (Lan or zeroiter).

**Comment by khayyamov** [comment]
I built Mieru a very simple API for mieru with gomobile you can use this in your xcode project for ios 
https://github.com/khayyamov/mieru/blob/main/API

**Comment by vostreltsov** [comment]
Excuse me for reviving this dead thread, but according to Shadowrocket release notes, they added support for mieru in version 2.2.85:

> feat(mieru): add support for Mieru protocol and its reliable UDP transport mode

Just mentioning this in case it helps someone
