### ISSUE TITLE
本机建立起mieru socks5链接之后，在clashx.pro客户端中无法使用tun模式

### ISSUE THREAD

**Issue by BoxXt** [enfein/mieru#63]
使用平台为macos系统 ，搭建好的mieru协议可用，但是作为clashx.pro中的socks5协议，clashx.pro无法开启tun模式，开启之后便无法使用。其他模式正常，猜测是mieru客户端监听socks5端口的部分有问题？
以下是clashx.pro的部分配置（clash配置通用）
proxies:
  
- name: mieru
  type: socks5
  server: 127.0.0.1
  port: 5080
  udp: true
  

proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - mieru

rules:
  - GEOIP,CN,DIRECT
  - MATCH,Proxy

**Comment by enfein** [comment]
tun 出现问题可能是因为 mieru outbound 的流量又进到了 tun 里面。

可以尝试下面几件事：

1. 打开 mieru 和 mita 的调试日志，看看服务器是否收到了请求。步骤可以在这里找到 https://github.com/enfein/mieru/blob/main/docs/operation.zh_CN.md
2. 用 wireshark 或者 tcpdump 抓包看看 mieru 出去的包去了哪里。
3. https://comzyh.gitbook.io/clash/ 或者会对你有帮助。

**Comment by BoxXt** [comment]
假如我在局域网内别的设备开启mieru就可以在本机设备上正常开启clashx的tun模式，请问应该如何避免mieru outbound的流量重新流进tun里面呢？

**Comment by BoxXt** [comment]
问题已解决，在clash的配置中添加 - IP-CIDR,xx.xx.xx.xx/32,DIRECT,no-resolve，其中ip修改为vps的ip地址就可以解决回环的问题了，目前测试同一vps，mieru的youtube速率是最高的，👍。
