### ISSUE TITLE
macos客户端

### ISSUE THREAD

**Issue by gray0128** [enfein/mieru#64]
感谢作者！
我看介绍里macos有客户端，但在GitHub Releases 页面并没有找到，是我哪里搞错了吗？

**Comment by enfein** [comment]
请打开 MacOS Terminal 并且运行两个指令 `uname -s` 和 `uname -m`.

如果运行结果是

```shell
$ uname -s
Darwin

$ uname -m
x86_64
```

请下载 https://github.com/enfein/mieru/releases/download/v1.13.0/mieru_1.13.0_darwin_amd64.tar.gz

如果运行结果是

```shell
$ uname -s
Darwin

$ uname -m
arm64
```

请下载 https://github.com/enfein/mieru/releases/download/v1.13.0/mieru_1.13.0_darwin_arm64.tar.gz

**Comment by gray0128** [comment]
谢谢！
