### ISSUE TITLE
mieru as system proxy

### ISSUE THREAD

**Issue by mohammadrndissco** [enfein/mieru#65]
is it possible to set mieru as system proxy?

**Comment by enfein** [comment]
Yes.

Set your OS to forward network traffic to the HTTP / HTTPS port that mieru client is listening to.

**Comment by U201413497** [comment]
https://github.com/U201413497/mieru-script
you can have a look this

**Comment by enfein** [comment]
@U201413497 Thank you for providing this! It saves some manual steps to enable and disable system proxy.
