### ISSUE TITLE
DOH

### ISSUE THREAD

**Issue by abbaszahiri** [enfein/mieru#67]
Here I know, they listen to DNS requests .

How can I have a configuration with DoH for example or another way to prevent Man In the Middle to listen my DNS requests?

**Comment by enfein** [comment]
If the socks5 request is using domain name destination, mieru client doesn't do DNS resolution, only mita server does DNS.

So if you want to avoid DNS leak or DNS hijack, you can deploy DNS server like `dnsmasq` in your **proxy server** to protect the resolution. It is outside the scope of this project.
