### ISSUE TITLE
怎么解决/var/run/mita.sock文件不存在的问题？

### ISSUE THREAD

**Issue by briteming** [enfein/mieru#7]
hi.

```
root@racknerd-7b97d8:~# mita apply config mita-server_config.json
get mieru server status failed: ServerLifecycleService.GetStatus() failed: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /var/run/mita.sock: connect: no such file or directory"
root@racknerd-7b97d8:~#
```

怎么解决/var/run/mita.sock文件不存在的问题？

**Comment by enfein** [comment]
Hi briteming,

`/var/run/mita.sock` 文件是服务端进程 mita 启动时创建的。如果没有这个文件，很可能是因为服务端没有启动，或者启动不正常。您是否可以分享 Linux 发行版的类别，如 Ubuntu，和下面几个指令的输出结果？我可以帮忙进行下一步的排查。

1. `mita status`
2. `systemctl status mita`
3. `journalctl -xe -u mita --no-pager`

关于第三个指令，如果太长可以导出为文件附件。在没有打开 DEBUG 调试日志的情况下，它不会泄露除了监听端口号之外的重要隐私，不过建议您把自认为不妥当的部分删去再贴过来。

谢谢

**Comment by briteming** [comment]
hi.

Linux 发行版的类别: ubuntu 18.04

root@racknerd-7b97d8:~# mita status
get mieru server status failed: ServerLifecycleService.GetStatus() failed: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /var/run/mita.sock: connect: no such file or directory"
root@racknerd-7b97d8:~# systemctl status mita
Unit mita.service could not be found.
root@racknerd-7b97d8:~# journalctl -xe -u mita --no-pager
-- Logs begin at Sat 2022-02-19 09:44:07 GMT, end at Sat 2022-04-23 10:57:14 BST. --
-- No entries --
root@racknerd-7b97d8:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
root@racknerd-7b97d8:~#

谢谢回复

**Comment by briteming** [comment]
我是用go get安装程序的。

**Comment by enfein** [comment]
我们建议使用 debian 安装包来安装 mita。如果不使用安装包，则要通过 root 用户进行一些额外的操作。需要做的步骤包括：

1. 添加一个叫 `mita` 的用户和对应的用户组。
2. 创建 `/etc/mita` 文件夹并赋予 775 权限。
3. 在另外一个窗口，运行 `./mita run` 启动服务端进程。

之后，就可以用文档中所述的方法继续配置和运行服务端软件了。

前两个步骤的具体指令，可以在项目目录下的 `build/package/mita/debian/DEBIAN/postinst` 文件中找到。

注意，如果不使用安装包，服务端进程将不会随系统一同启动。重启系统之后，需要再次运行 `./mita run` 启动服务端进程。

**Comment by briteming** [comment]
hi.

这次搞定了。不过服务器上，运行mita run & ，mita还是容易退出。我想写一个mita.service文件，该怎么写？

**Comment by briteming** [comment]
会写mita.service文件了

**Comment by enfein** [comment]
可以参考 `build/package/mita/debian/lib/systemd/system/mita.service`
