### ISSUE TITLE
adding routing functionality

### ISSUE THREAD

**Issue by U201413497** [enfein/mieru#70]
Are you considering adding routing functionality?
Such as using geoip and geosite

**Comment by enfein** [comment]
I don't have a timeline to do that. It is easy to combine mieru with v2ray / clash / sing-box to achieve that.

**Comment by U201413497** [comment]
> I don't have a timeline to do that. It is easy to combine mieru with v2ray / clash / sing-box to achieve that.


I know what you mean, but this method requires two pieces of software, which is inconvenient.
