### ISSUE TITLE
Limit for user connection 

### ISSUE THREAD

**Issue by ximanj** [enfein/mieru#72]
First of all thank you for your great job. 🙏🙏
Is there any solution to limit number of devices connecting trough same user config to prevent sharing their credentials with others?
@enfein

**Comment by enfein** [comment]
There is no such support.

**Comment by enfein** [comment]
You can have one user per registered account, but there is no easy way to prevent this account being shared. Netflix has the same problem.

**Comment by enfein** [comment]
The only thing we have is traffic metrics (RX/TX bytes) per user.
