### ISSUE TITLE
Considering developing an openwrt plugin?

### ISSUE THREAD

**Issue by U201413497** [enfein/mieru#75]
Are you considering developing an openwrt plugin? In this way, it is more convenient to use on the router.

**Comment by enfein** [comment]
Do you mean package mieru such that it can be installed with `opkg` command?

I need to do some investigation. I believe it should be easy to copy some files and run mieru on openwrt.

**Comment by enfein** [comment]
Added some documents about install mieru to OpenWrt with existing builds.

**Comment by U201413497** [comment]
For example, using trojan, https://github.com/frainzy1477/luci-app-trojan, similarly, using mieru, you can also have a luci-app-mieru.  you can also seek cooperation from helloworld, https://github.com/fw876/helloworld

**Comment by enfein** [comment]
I can't promise when we will have that. The roadmap in 2024 is release mieru v2 and release windows and android app. OpenWrt is not a priority.
