### ISSUE TITLE
Mita是否可以指定出站流量或透過其他應用代理？

### ISSUE THREAD

**Issue by yatounoneko** [enfein/mieru#76]
例如使用WARP+解鎖某些應用，而WARP也提供了Local Proxy。

但mita的配置文件我似乎沒看到有能夠指定出站或二級代理的配置。
因此想請教一下是否有相應的配置，或透過其他應用能指定出站流量？

**Comment by yatounoneko** [comment]
抱歉，有些不明白的地方，我的構想是：
`(客戶端)mieru -> mita(服務端) -> WARP(客戶端，提供本地socks5/http服務) -> Internet -> WARP Server` 
那麼理應mieru客戶端得到的應該是WARP Server 的IP。

因爲warp本身是個客戶端，但提供http或socks5的的本地代理模式而不會接管所有流量(TUN會導致mita無法與mieru連接)。
mita可以透過配置文件添加sock5代理，連接warp客戶端提供的本地socks5做爲出站嗎？

**Comment by enfein** [comment]
WARP 客户端是运行在本地还是运行在云上？如果是运行在本地，那么根本不需要 mieru 和 mita, 直接连 WARP 客户端就可以了。

**Comment by enfein** [comment]
可能的解决方案：https://embiid.blog/post/WARP-does-not-work-after-submitting-an-invite-code/ 方法一

拓扑结构应该是 wrap client -- mieru -- mita -- cloudflare -- destination

**Comment by enfein** [comment]
类似的讨论：https://github.com/warpdotdev/Warp/issues/705#issuecomment-1358155389

**Comment by yatounoneko** [comment]
Oh，是我沒講清楚，WARP是指Cloudflare WARP。
Cloudflare WARP本身是類似隧道的服務，它能讓客戶端透過Cloudflare提供的IP代理客戶端流量。

而本身Cloudflare Warp也有提供本地socks5端口給其他應用進行二級代理，所以我在想能不能在mita服務器配置cloudflare warp，而mita作爲前置服務讓mieru能夠透過cloudflare IP訪問互聯網。

簡單來說，當mieru連接到mita後，mita將出站流量中轉給cloudflare warp客戶端提供的本地socks5代理。
然後mieru理應獲得cloudflare IP而不是mita本機的IP，大概是這麼一個意思。

**Comment by yatounoneko** [comment]
Wait #77 to resolve
