### ISSUE TITLE
How to limit traffic?

### ISSUE THREAD

**Issue by cr4zyfish** [enfein/mieru#79]
How to limit each user's traffic per MB or GB ?

**Comment by enfein** [comment]
We will add this feature when mieru v2 is released. mieru v2 allows server to send error message to client.

**Comment by freenet4ever** [comment]
> We will add this feature when mieru v2 is released. mieru v2 allows server to send error message to client.

Hi
Can you tell how to do it now with mieru v 2.0?

**Comment by enfein** [comment]
@freenet4ever I am still working on the development. Most likely this will be added in v2.1.0.

**Comment by yatounoneko** [comment]
> We will add this feature when mieru v2 is released. mieru v2 allows server to send error message to client.

Just a question, If the server will send error message to client, does it mean that in some cases gfw is able to get some information through active attacks to block connection?

For the v1, When the server can not decrypt the data sent by the client, no content is returned. This feature also available on this case(v2)?

**Comment by enfein** [comment]
> Just a question, If the server will send error message to client, does it mean that in some cases gfw is able to get some information through active attacks to block connection?

Server only send response if the server is able to decrypt, and it is not a replay.
