### ISSUE TITLE
HTTP proxy problem

### ISSUE THREAD

**Issue by cr4zyfish** [enfein/mieru#80]
![image](https://github.com/enfein/mieru/assets/90797624/ba04fa7d-bd37-4f56-99be-4e764e12b5b8)

With HTTP proxy sometimes a gz file of page is downloaded instead of diplaying the page in browser.

**Comment by enfein** [comment]
@cr4zyfish 

1. Please share the OS, browser name and mieru version.
2. Is this reproducible? For the website that is problematic, if you open multiple times, is it continuously downloading a gz file? Is it downloading the gz file in some cases and show the web page in other cases? Do you have an example of such web page?

Thanks

**Comment by cr4zyfish** [comment]
OS: Windows 10
Browser: chrome and firefox
mieru client:    
MD5: f2276c6c6e0fb7113400a68f9c435fe9
SHA-1: 3e4d10c55cd94082e214e15ab3faea793bb20edf

mita Server: 1.14.1

I dont know how to reproduce this, it doesnt happen to HTTPS websites, but all HTTP websites it happens multiple times. for example:

http://example.com/ 
downloads a gz file

FIrefox:
![image](https://github.com/enfein/mieru/assets/90797624/f4912c13-026f-43ee-80f3-a4505e3d87cc)

The name of downloded file in firefox is different each time. 


Chrome:
![image](https://github.com/enfein/mieru/assets/90797624/95582a3b-37a5-4574-87a1-ed1f298565e2)

But with HTTPS it is opened normaly.

Also another problem: when I set mieru as socks proxy (socks port) in openvpn it is not connecting to vpn server but when I set HTTP port of mieru it connects. what is the reason?

**Comment by enfein** [comment]
This is a bug. Working on the fix now.

Regarding OpenVPN, does it expect socks5 protocol or HTTP(S) protocol? I know OS system proxy always uses HTTP(S) protocol.

**Comment by enfein** [comment]
Version 1.15.1 should fix this issue. Please check.

Thanks!

**Comment by cr4zyfish** [comment]
Thanks, I think for windows the problem was openvpn connect does not support socks proxy but openvpn comunity does. So the problem is not related to mieru.
