### ISSUE TITLE
mieru is occasionally blocked in iran due to regional network disruption

### ISSUE THREAD

**Issue by cr4zyfish** [enfein/mieru#81]
I was using this for a while but now it is blocked in iran. how to identify the method they used to block it? 
the ip address of server is not blocked because http and ssh works but mieru not working with iranian internet. Some packets are sent and recevied between mieru client and server but no website can be opened.

**Comment by enfein** [comment]
@cr4zyfish 

Please help us to investigate on this:

1. Share the version number of mita and mieru.
2. Share the log of mita and mieru. The steps to collect log are described in the Maintenance & Troubleshooting document. We need at least one full snapshot of metrics in the log. We can dig more information if you enabled DEBUG log, like what we did in issue #50, but be sure to redact IP addresses in that case.
3. Share the protocol you are using. It is either TCP or UDP.

The following symptoms may indicate the proxy is blocked:

1. The `NewSession` and `KnownSession` in replay metrics are bigger than 0.
2. When you change the port number, you no longer get blocked, but you get blocked again after some time.
3. If you specify a lot of ports, for example > 10 ports, you no longer get blocked.

**Comment by cr4zyfish** [comment]
It is working now. I think it was temporary block due to anniversary of protests in iran. We had some problems in internet for the last days:

![1111](https://github.com/enfein/mieru/assets/90797624/0ad162ee-6c8e-4e99-b199-9f312103f5df)

![22222](https://github.com/enfein/mieru/assets/90797624/a88bc5c5-1d80-496a-9bb1-e96278966f1c)


![3333](https://github.com/enfein/mieru/assets/90797624/55a6fde6-6457-4ee2-9cbc-840f7a94e717)

I think they interrupted any suspicious encrypted traffic but im not sure if they can detect its mieru traffic or not. I have to wait and see if they do this again to test your comment.

**Comment by enfein** [comment]
@cr4zyfish 

Can you help to check if the `NewSession` and `KnownSession` in replay metrics have non zero values?

If those values are 0, then GFW didn't attempt to probe the proxy with a replay attack, and there is nothing more we can do.

**Comment by cr4zyfish** [comment]
Do you mean by running these commands? 
sudo journalctl -u mita -xe --no-pager | grep KnownSession
journalctl -u mita -xe --no-pager | grep NewSession

Out put:

Sep 15 00:00:00 mydomain.com mita[16290]: INFO [metrics - replay] KnownSession=0 NewSession=0
Sep 15 00:00:00 mydomain.com mita[16290]: INFO [metrics - replay] KnownSession=0 NewSession=0

[I removed my domain and time].

 it started from some time in Sep 15 and there are logs like this for about two hours. only in sep 15.

**Comment by enfein** [comment]
> all of them are = 0

This is good. GFW didn't notice and didn't probe the proxy with a replay attack.

> why there are logs only for sep 15?

The log should continue to print every minute as long as mita server is in running state, regardless whether there is incoming connections. Can you check the output of the following commands?

```
# check if proxy server is running
mita status
```

```
# print and continue to follow the log
# the last line tells you the latest log timestamp
sudo journalctl -fu mita --no-pager
```

You can also try reboot your server again and run those commands. The expectation is, after reboot, mita should start automatically, print logs, and ready to serve client requests.

**Comment by enfein** [comment]
Closing this for now. Please try mieru 2.0.0 and see if it works better.
