### ISSUE TITLE
mieru v2 android

### ISSUE THREAD

**Issue by dopraxerz** [enfein/mieru#84]
Is any plugin available for android (v 2.0)

**Comment by enfein** [comment]
As of today, there is no Android plugin for mieru v2.

I will chat with other developers and see if we can have a mieru plugin in https://github.com/MatsuriDayo/NekoBoxForAndroid

In the meanwhile, I will develop a minimal Android app that runs mieru v2, similar to outline.

**Comment by PharosVip** [comment]
Try with mieru://server:port?username=john&password=secret&network=tcp#GoogleVps in [Routen app](https://github.com/enfein/mieru/discussions/60#discussioncomment-7302288)

**Comment by enfein** [comment]
We will track this in issue #89
