### ISSUE TITLE
centos7 使用mieru连接报错，麻烦看看

### ISSUE THREAD

**Issue by mm8m6m7m** [enfein/mieru#85]
centos7 使用mieru连接报错，麻烦看看：
Oct 09 22:19:07 test mita[22922]: DEBUG socks5 server listener [::]:2023 ServeConn() failed: failed to get version byte: cipher.SelectDecrypt() failed: unable to decrypt from supplied 6 cipher blocks

**Comment by enfein** [comment]
不能解密有两种可能。第一种是用户名密码不匹配。用 `mieru describe config` 和 `mita describe config` 看一下用户名和密码是不是一样的。第二种是两台机器的时间不一致。两台机器的时间差超过两分钟就会连不上。

**Comment by mm8m6m7m** [comment]
@enfein 我看看服务端和本地时间  如果不行再联系您  辛苦

**Comment by mm8m6m7m** [comment]
客户端配置：
![image](https://github.com/enfein/mieru/assets/20329685/20dcc390-80d4-4096-ad8b-e9c30020c334)
服务端配置：
![image](https://github.com/enfein/mieru/assets/20329685/4c48fa58-01ca-4e4e-b194-f649e01161f5)
两边时间
![image](https://github.com/enfein/mieru/assets/20329685/e0efa669-b4ea-4891-9023-88e39fdbec7f)
![image](https://github.com/enfein/mieru/assets/20329685/9a31709d-a77c-495f-8d4b-465d5ab6630a)
还是有报错的，这个linux的客户端有实际使用的说明吗 @enfein

**Comment by mm8m6m7m** [comment]
我试了使用这个客户端配置 用win的客户端是没有问题的 @enfein

**Comment by mm8m6m7m** [comment]
同一份配置 win客户端和安卓的都测试了 都没问题，只有linux的客户端有问题，这个linux的客户端有测试过的吗？ @enfein

**Comment by enfein** [comment]
我的开发机用的是 Linux 系统，我用 mieru + Tor 浏览器没有问题。你的客户端和服务器装的是同一个版本么？

**Comment by mm8m6m7m** [comment]
服务器用centos7.9  客户端也是centos7.9 @enfein 有其它用户反馈过类似的问题吗？

**Comment by mm8m6m7m** [comment]
服务器是centos7.9 我在win11下用mieru的同一份配置都可以使用，就是到了linux客户端无法使用。

**Comment by enfein** [comment]
和 CentOS 的版本没有关系。

请在 Linux 客户端电脑上和 Win 上运行 `mieru version` 指令，然后在 Linux 服务器上运行 `mita version` 指令。看看大家的版本是不是一样的。如果其中一个是 1.x.y 版本一个是 2.0.0 版本，两个是不兼容的。

**Comment by enfein** [comment]
如果所有地方的版本号都是一样的，且重新安装 mieru 和 mita 也不能解决，那么应该是有 bug，但是很可惜我没有办法复现，之前也没有听到过别人有类似的问题。

**Comment by mm8m6m7m** [comment]
确实是版本不同造成的，linux客户端使用了2.0.0的版本。mita的版本和windows系统的客户端版本都是1.5.0.全部换成一样就可以了，感谢处理。
