### ISSUE TITLE
Windows run in background

### ISSUE THREAD

**Issue by dopraxerz** [enfein/mieru#87]
Is any way to run mieru without a cmd window being open?

**Comment by enfein** [comment]
This may be helpful: https://github.com/enfein/mieru/issues/43#issuecomment-1348794048

**Comment by enfein** [comment]
I am not a Windows expert. If you figure out a good solution, feel free to contribute to the docs.

**Comment by freenet4ever** [comment]
> Is any way to run mieru without a cmd window being open?
It is possible with a .vbs file:

```
Set WshShell = CreateObject("WScript.Shell" ) 
WshShell.Run chr(34) & "C:\Users\mieru\mieru.bat" & Chr(34), 0 
Set WshShell = Nothing 
```

But Microsoft is going to kill VBScript:
https://www.bleepingcomputer.com/news/security/microsoft-to-kill-off-vbscript-in-windows-to-block-malware-delivery/

**Comment by re-move** [comment]
> > Is any way to run mieru without a cmd window being open?
> 
> It is possible with a .vbs file:
> 
> ```
> Set WshShell = CreateObject("WScript.Shell" ) 
> WshShell.Run chr(34) & "C:\Users\mieru\mieru.bat" & Chr(34), 0 
> Set WshShell = Nothing 
> ```
> 
> But Microsoft is going to kill VBScript: https://www.bleepingcomputer.com/news/security/microsoft-to-kill-off-vbscript-in-windows-to-block-malware-delivery/

https://github.com/enfein/mieru/issues/43#issuecomment-1776082323

**Comment by dopraxerz** [comment]
> I am not a Windows expert. If you figure out a good solution, feel free to contribute to the docs.

The method I use now:
I have a folder called mieru. Inside folder there are 3 files:

config.json
mieru.bat
mieru.exe

The content of mieru.bat is:

```
mieru.exe apply config config.json
mieru.exe start
```

I have a vbs file here:
`C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp`

the content of mieru.vbs:

```
Set WshShell = CreateObject("WScript.Shell" ) 
WshShell.Run chr(34) & "C:\users\mieru\Documents\mieru\mieru.bat" & Chr(34), 0 
Set WshShell = Nothing 
```

When I start windows, mieru works in background. you can close it by task manager if you need to change config.
