### ISSUE TITLE
Adding user

### ISSUE THREAD

**Issue by dopraxerz** [enfein/mieru#88]
Does adding a new user and applying config desrupts active connections?

**Comment by enfein** [comment]
No. Server doesn't reload the new configuration when you call `mite apply config ...`, so there is no disruption to existing connections. If you want a hot reload feature, I can work on it.

**Comment by dopraxerz** [comment]
I want to be able to delete and add users without distuption to connections. Is this possible just with mita apply config ...?  how can I get current traffic used by each user and days remaining?

**Comment by enfein** [comment]
@dopraxerz I will do it in issue #93.
