### ISSUE TITLE
Feature: Add Mieru to Nekobox

### ISSUE THREAD

**Issue by ellahmezar** [enfein/mieru#89]
Hi , 
It will be great if you talk to Nekobox supervisors ,and add this wonderful feature to Nekobox .
@enfein

**Comment by enfein** [comment]
You can download preview APKs from issue #99 now.

**Comment by ellahmezar** [comment]
@enfein 
Hi  , 
Many thanks .
I downloaded the issue #99 and installed the apk , and ran miero on my server , but this error apears .
What's the problem ?

![Screenshot_20231212_141715_NekoBox](https://github.com/enfein/mieru/assets/129280842/c8a08585-6754-4d39-9c95-5f432cd36c44)

**Comment by enfein** [comment]
@ellahmezar If you install both APK files it should work.

If not, then you might need to clean the data of the previous NekoBox app. We have changed the database schema, and it may not be able to recognize the new plugin.

**Comment by ellahmezar** [comment]
@enfein 
Hi, 
I didn't install the second file (plugin) :)))
It works now ,but the ping is about 340 in Nekobox ( Despite TUIC ping is about 140 )

1 / Can you do something that people can connect to Mieru in Nekobox "WITHOUT PLUGIN" ? ( I mean directly like other connection ways exist in Nekobox like vless , vmess & . . . )
2 / Can you do something that reduces the ping Nekobox shown ? ( 340 is high in comparison of TUIC & Hysteria 2 that their ping is 150 in Nekobox )

Many thanks my dear friend , May God be with you .

**Comment by enfein** [comment]
If mieru becomes popular such that it is added to sing-box, then the plugin APK is no longer needed and the ping can be reduced. I will keep maintaining the software and wait for that to happen.

**Comment by ellahmezar** [comment]
@enfein 
Many thanks.
I forgot to say , the upload speed is too weak in comparison with TUIC & Hysteria 2 plugins .
Also the real ping is 30 ms higher than TUIC & Hysteria

**Comment by enfein** [comment]
You may want to try mieru TCP protocol, which is typically faster than UDP.

TUIC handshake is 0-RTT, so the real ping difference is like 140 vs 170. mieru deliberately chose 1-RTT handshake in order to preserve behaviors of socks5 protocol.

**Comment by enfein** [comment]
The programming work is done. The only missing piece is a new NekoBox release. For now, use instructions in issue #99 to run mieru in Android.
