### ISSUE TITLE
咨询确认 - 纯ipv6的VPS搭建后，windows客户端无法连接

### ISSUE THREAD

**Issue by youjiajia-wc** [enfein/mieru#9]
vps服务端为纯ipv6机器，root安装后，mita status的结果为mieru server status is "IDLE"。配置服务端json，启动后，正常为RUNNING
windows配置文件在最后，由于隐私，地址改为ipv6的字符串，以下是客户端的部分日志
确认客户端可以ping通服务端的ipv6地址
2022-05-22T03:50:19+08:00 INFO [metrics - server decryption] ServerDirectDecrypt=0 ServerFailedDirectDecrypt=0
2022-05-22T03:50:19+08:00 INFO [metrics - client decryption] ClientDirectDecrypt=16 ClientFailedDirectDecrypt=0

以下是客户端配置
```
{
    "profiles": [
        {
            "profileName": "default",
            "user": {
                "name": "a",
                "password": "123"
            },
            "servers": [
                {
                    "ipAddress": "ipv6",
                    "domainName": "",
                    "portBindings": [
                        {
                            "port": 10000,
                            "protocol": "TCP"
                        }
                    ]
                }
            ]
        }
    ],
    "activeProfile": "default",
    "rpcPort": 20000,
    "socks5Port": 30000,
    "loggingLevel": "INFO"
}
```

**Comment by enfein** [comment]
youjiajia-wc 你好，

根据 `ClientDirectDecrypt=16` 看起来客户端有成功收到服务器发回的信息。你说的 windows 客户端无法连接，具体有哪些症状？

另外，能否分享客户端和服务端下面几行日志的信息？

```
INFO [metrics - connections] ActiveOpens=28 CurrEstablished=2 MaxConn=17 PassiveOpens=0
INFO [metrics - TCP bytes] InBytes=452167942 OutBytes=439188 PaddingSent=26870
INFO [metrics - error] KCPInErrors=0 KCPReceiveErrors=0 KCPSendErrors=0 TCPReceiveErrors=26 TCPSendErrors=0 UDPInErrors=0
```

谢谢！

不能保证每天上线，下次上线会及时回复。

**Comment by youjiajia-wc** [comment]
这条是客户端日志
2022-05-22T15:12:37+08:00 INFO mieru client RPC server is running
2022-05-22T15:12:37+08:00 INFO mieru client socks5 server is running
2022-05-22T15:12:37+08:00 INFO enabled metrics logging with duration 1m0s
2022-05-22T15:12:37+08:00 INFO return app status RUNNING back to RPC caller
2022-05-22T15:12:46+08:00 INFO return app status RUNNING back to RPC caller
2022-05-22T15:13:37+08:00 INFO [metrics]
2022-05-22T15:13:37+08:00 INFO [metrics - connections] ActiveOpens=1 CurrEstablished=1 MaxConn=1 PassiveOpens=0
2022-05-22T15:13:37+08:00 INFO [metrics - server decryption] ServerDirectDecrypt=0 ServerFailedDirectDecrypt=0
2022-05-22T15:13:37+08:00 INFO [metrics - client decryption] ClientDirectDecrypt=0 ClientFailedDirectDecrypt=0
2022-05-22T15:13:37+08:00 INFO [metrics - UDP packets] InPkts=0 OutPkts=0
2022-05-22T15:13:37+08:00 INFO [metrics - KCP segments] EarlyRetransSegs=0 FastRetransSegs=0 InSegs=0 LostSegs=0 OutOfWindowSegs=0 OutSegs=0 RepeatSegs=0 RetransSegs=0
2022-05-22T15:13:37+08:00 INFO [metrics - UDP bytes] InBytes=0 OutBytes=0
2022-05-22T15:13:37+08:00 INFO [metrics - KCP bytes] BytesReceived=0 BytesSent=0 PaddingSent=0
2022-05-22T15:13:37+08:00 INFO [metrics - TCP bytes] InBytes=0 OutBytes=77 PaddingSent=24
2022-05-22T15:13:37+08:00 INFO [metrics - replay protection] ReplayKnownSession=0 ReplayNewSession=0
2022-05-22T15:13:37+08:00 INFO [metrics - error] KCPInErrors=0 KCPReceiveErrors=0 KCPSendErrors=0 TCPReceiveErrors=0 TCPSendErrors=0 UDPInErrors=0
2022-05-22T15:14:37+08:00 INFO [metrics]
2022-05-22T15:14:37+08:00 INFO [metrics - connections] ActiveOpens=9 CurrEstablished=0 MaxConn=3 PassiveOpens=0
2022-05-22T15:14:37+08:00 INFO [metrics - server decryption] ServerDirectDecrypt=0 ServerFailedDirectDecrypt=0
2022-05-22T15:14:37+08:00 INFO [metrics - client decryption] ClientDirectDecrypt=36 ClientFailedDirectDecrypt=0
2022-05-22T15:14:37+08:00 INFO [metrics - UDP packets] InPkts=0 OutPkts=0
2022-05-22T15:14:37+08:00 INFO [metrics - KCP segments] EarlyRetransSegs=0 FastRetransSegs=0 InSegs=0 LostSegs=0 OutOfWindowSegs=0 OutSegs=0 RepeatSegs=0 RetransSegs=0
2022-05-22T15:14:37+08:00 INFO [metrics - UDP bytes] InBytes=0 OutBytes=0
2022-05-22T15:14:37+08:00 INFO [metrics - KCP bytes] BytesReceived=0 BytesSent=0 PaddingSent=0
2022-05-22T15:14:37+08:00 INFO [metrics - TCP bytes] InBytes=1738 OutBytes=2090 PaddingSent=1047
2022-05-22T15:14:37+08:00 INFO [metrics - replay protection] ReplayKnownSession=0 ReplayNewSession=0
2022-05-22T15:14:37+08:00 INFO [metrics - error] KCPInErrors=0 KCPReceiveErrors=0 KCPSendErrors=0 TCPReceiveErrors=1 TCPSendErrors=0 UDPInErrors=0
2022-05-22T15:15:37+08:00 INFO [metrics]
2022-05-22T15:15:37+08:00 INFO [metrics - connections] ActiveOpens=9 CurrEstablished=0 MaxConn=3 PassiveOpens=0
2022-05-22T15:15:37+08:00 INFO [metrics - server decryption] ServerDirectDecrypt=0 ServerFailedDirectDecrypt=0
2022-05-22T15:15:37+08:00 INFO [metrics - client decryption] ClientDirectDecrypt=36 ClientFailedDirectDecrypt=0
2022-05-22T15:15:37+08:00 INFO [metrics - UDP packets] InPkts=0 OutPkts=0
2022-05-22T15:15:37+08:00 INFO [metrics - KCP segments] EarlyRetransSegs=0 FastRetransSegs=0 InSegs=0 LostSegs=0 OutOfWindowSegs=0 OutSegs=0 RepeatSegs=0 RetransSegs=0
2022-05-22T15:15:37+08:00 INFO [metrics - UDP bytes] InBytes=0 OutBytes=0
2022-05-22T15:15:37+08:00 INFO [metrics - KCP bytes] BytesReceived=0 BytesSent=0 PaddingSent=0
2022-05-22T15:15:37+08:00 INFO [metrics - TCP bytes] InBytes=1738 OutBytes=2090 PaddingSent=1047
2022-05-22T15:15:37+08:00 INFO [metrics - replay protection] ReplayKnownSession=0 ReplayNewSession=0
2022-05-22T15:15:37+08:00 INFO [metrics - error] KCPInErrors=0 KCPReceiveErrors=0 KCPSendErrors=0 TCPReceiveErrors=1 TCPSendErrors=0 UDPInErrors=0

**Comment by youjiajia-wc** [comment]
这条是服务端日志
May 22 15:11:04 unl-server-factory systemd[1]: Starting Mieru proxy server...
░░ Subject: A start job for unit mita.service has begun execution
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A start job for unit mita.service has begun execution.
░░ 
░░ The job identifier is 928.
May 22 15:11:04 unl-server-factory mita[1254]: 2022-05-22T15:11:04+08:00 INFO mieru server daemon RPC server is running
May 22 15:11:04 unl-server-factory mita[1254]: 2022-05-22T15:11:04+08:00 INFO mieru server daemon socks5 server "[::]:10000" is running
May 22 15:11:04 unl-server-factory mita[1254]: 2022-05-22T15:11:04+08:00 INFO enabled metrics logging with duration 1m0s
May 22 15:11:04 unl-server-factory systemd[1]: Started Mieru proxy server.
░░ Subject: A start job for unit mita.service has finished successfully
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A start job for unit mita.service has finished successfully.
░░ 
░░ The job identifier is 928.
May 22 15:11:25 unl-server-factory mita[1254]: 2022-05-22T15:11:25+08:00 INFO return app status RUNNING back to RPC caller
May 22 15:11:59 unl-server-factory mita[1254]: 2022-05-22T15:11:59+08:00 INFO return app status RUNNING back to RPC caller
May 22 15:12:04 unl-server-factory mita[1254]: 2022-05-22T15:12:04+08:00 INFO [metrics]
May 22 15:12:04 unl-server-factory mita[1254]: 2022-05-22T15:12:04+08:00 INFO [metrics - connections] ActiveOpens=0 CurrEstablished=0 MaxConn=0 PassiveOpens=0
May 22 15:12:04 unl-server-factory mita[1254]: 2022-05-22T15:12:04+08:00 INFO [metrics - server decryption] ServerDirectDecrypt=0 ServerFailedDirectDecrypt=0
May 22 15:12:04 unl-server-factory mita[1254]: 2022-05-22T15:12:04+08:00 INFO [metrics - client decryption] ClientDirectDecrypt=0 ClientFailedDirectDecrypt=0
May 22 15:12:04 unl-server-factory mita[1254]: 2022-05-22T15:12:04+08:00 INFO [metrics - UDP packets] InPkts=0 OutPkts=0
May 22 15:12:04 unl-server-factory mita[1254]: 2022-05-22T15:12:04+08:00 INFO [metrics - KCP segments] EarlyRetransSegs=0 FastRetransSegs=0 InSegs=0 LostSegs=0 OutOfWindowSegs=0 OutSegs=0 RepeatSegs=0 RetransSegs=0
May 22 15:12:04 unl-server-factory mita[1254]: 2022-05-22T15:12:04+08:00 INFO [metrics - UDP bytes] InBytes=0 OutBytes=0
May 22 15:12:04 unl-server-factory mita[1254]: 2022-05-22T15:12:04+08:00 INFO [metrics - KCP bytes] BytesReceived=0 BytesSent=0 PaddingSent=0
May 22 15:12:04 unl-server-factory mita[1254]: 2022-05-22T15:12:04+08:00 INFO [metrics - TCP bytes] InBytes=0 OutBytes=0 PaddingSent=0
May 22 15:12:04 unl-server-factory mita[1254]: 2022-05-22T15:12:04+08:00 INFO [metrics - replay protection] ReplayKnownSession=0 ReplayNewSession=0
May 22 15:12:04 unl-server-factory mita[1254]: 2022-05-22T15:12:04+08:00 INFO [metrics - error] KCPInErrors=0 KCPReceiveErrors=0 KCPSendErrors=0 TCPReceiveErrors=0 TCPSendErrors=0 UDPInErrors=0
May 22 15:13:04 unl-server-factory mita[1254]: 2022-05-22T15:13:04+08:00 INFO [metrics]
May 22 15:13:04 unl-server-factory mita[1254]: 2022-05-22T15:13:04+08:00 INFO [metrics - connections] ActiveOpens=0 CurrEstablished=0 MaxConn=0 PassiveOpens=0
May 22 15:13:04 unl-server-factory mita[1254]: 2022-05-22T15:13:04+08:00 INFO [metrics - server decryption] ServerDirectDecrypt=0 ServerFailedDirectDecrypt=0
May 22 15:13:04 unl-server-factory mita[1254]: 2022-05-22T15:13:04+08:00 INFO [metrics - client decryption] ClientDirectDecrypt=0 ClientFailedDirectDecrypt=0
May 22 15:13:04 unl-server-factory mita[1254]: 2022-05-22T15:13:04+08:00 INFO [metrics - UDP packets] InPkts=0 OutPkts=0
May 22 15:13:04 unl-server-factory mita[1254]: 2022-05-22T15:13:04+08:00 INFO [metrics - KCP segments] EarlyRetransSegs=0 FastRetransSegs=0 InSegs=0 LostSegs=0 OutOfWindowSegs=0 OutSegs=0 RepeatSegs=0 RetransSegs=0
May 22 15:13:04 unl-server-factory mita[1254]: 2022-05-22T15:13:04+08:00 INFO [metrics - UDP bytes] InBytes=0 OutBytes=0
May 22 15:13:04 unl-server-factory mita[1254]: 2022-05-22T15:13:04+08:00 INFO [metrics - KCP bytes] BytesReceived=0 BytesSent=0 PaddingSent=0
May 22 15:13:04 unl-server-factory mita[1254]: 2022-05-22T15:13:04+08:00 INFO [metrics - TCP bytes] InBytes=0 OutBytes=0 PaddingSent=0
May 22 15:13:04 unl-server-factory mita[1254]: 2022-05-22T15:13:04+08:00 INFO [metrics - replay protection] ReplayKnownSession=0 ReplayNewSession=0
May 22 15:13:04 unl-server-factory mita[1254]: 2022-05-22T15:13:04+08:00 INFO [metrics - error] KCPInErrors=0 KCPReceiveErrors=0 KCPSendErrors=0 TCPReceiveErrors=0 TCPSendErrors=0 UDPInErrors=0
May 22 15:14:04 unl-server-factory mita[1254]: 2022-05-22T15:14:04+08:00 INFO [metrics]
May 22 15:14:04 unl-server-factory mita[1254]: 2022-05-22T15:14:04+08:00 INFO [metrics - connections] ActiveOpens=0 CurrEstablished=0 MaxConn=3 PassiveOpens=9
May 22 15:14:04 unl-server-factory mita[1254]: 2022-05-22T15:14:04+08:00 INFO [metrics - server decryption] ServerDirectDecrypt=27 ServerFailedDirectDecrypt=0
May 22 15:14:04 unl-server-factory mita[1254]: 2022-05-22T15:14:04+08:00 INFO [metrics - client decryption] ClientDirectDecrypt=0 ClientFailedDirectDecrypt=0
May 22 15:14:04 unl-server-factory mita[1254]: 2022-05-22T15:14:04+08:00 INFO [metrics - UDP packets] InPkts=0 OutPkts=0
May 22 15:14:04 unl-server-factory mita[1254]: 2022-05-22T15:14:04+08:00 INFO [metrics - KCP segments] EarlyRetransSegs=0 FastRetransSegs=0 InSegs=0 LostSegs=0 OutOfWindowSegs=0 OutSegs=0 RepeatSegs=0 RetransSegs=0
May 22 15:14:04 unl-server-factory mita[1254]: 2022-05-22T15:14:04+08:00 INFO [metrics - UDP bytes] InBytes=0 OutBytes=0
May 22 15:14:04 unl-server-factory mita[1254]: 2022-05-22T15:14:04+08:00 INFO [metrics - KCP bytes] BytesReceived=0 BytesSent=0 PaddingSent=0
May 22 15:14:04 unl-server-factory mita[1254]: 2022-05-22T15:14:04+08:00 INFO [metrics - TCP bytes] InBytes=2090 OutBytes=1738 PaddingSent=838
May 22 15:14:04 unl-server-factory mita[1254]: 2022-05-22T15:14:04+08:00 INFO [metrics - replay protection] ReplayKnownSession=0 ReplayNewSession=0
May 22 15:14:04 unl-server-factory mita[1254]: 2022-05-22T15:14:04+08:00 INFO [metrics - error] KCPInErrors=0 KCPReceiveErrors=0 KCPSendErrors=0 TCPReceiveErrors=0 TCPSendErrors=0 UDPInErrors=0
May 22 15:15:04 unl-server-factory mita[1254]: 2022-05-22T15:15:04+08:00 INFO [metrics]
May 22 15:15:04 unl-server-factory mita[1254]: 2022-05-22T15:15:04+08:00 INFO [metrics - connections] ActiveOpens=0 CurrEstablished=0 MaxConn=3 PassiveOpens=9
May 22 15:15:04 unl-server-factory mita[1254]: 2022-05-22T15:15:04+08:00 INFO [metrics - server decryption] ServerDirectDecrypt=27 ServerFailedDirectDecrypt=0
May 22 15:15:04 unl-server-factory mita[1254]: 2022-05-22T15:15:04+08:00 INFO [metrics - client decryption] ClientDirectDecrypt=0 ClientFailedDirectDecrypt=0
May 22 15:15:04 unl-server-factory mita[1254]: 2022-05-22T15:15:04+08:00 INFO [metrics - UDP packets] InPkts=0 OutPkts=0
May 22 15:15:04 unl-server-factory mita[1254]: 2022-05-22T15:15:04+08:00 INFO [metrics - KCP segments] EarlyRetransSegs=0 FastRetransSegs=0 InSegs=0 LostSegs=0 OutOfWindowSegs=0 OutSegs=0 RepeatSegs=0 RetransSegs=0
May 22 15:15:04 unl-server-factory mita[1254]: 2022-05-22T15:15:04+08:00 INFO [metrics - UDP bytes] InBytes=0 OutBytes=0
May 22 15:15:04 unl-server-factory mita[1254]: 2022-05-22T15:15:04+08:00 INFO [metrics - KCP bytes] BytesReceived=0 BytesSent=0 PaddingSent=0
May 22 15:15:04 unl-server-factory mita[1254]: 2022-05-22T15:15:04+08:00 INFO [metrics - TCP bytes] InBytes=2090 OutBytes=1738 PaddingSent=838
May 22 15:15:04 unl-server-factory mita[1254]: 2022-05-22T15:15:04+08:00 INFO [metrics - replay protection] ReplayKnownSession=0 ReplayNewSession=0
May 22 15:15:04 unl-server-factory mita[1254]: 2022-05-22T15:15:04+08:00 INFO [metrics - error] KCPInErrors=0 KCPReceiveErrors=0 KCPSendErrors=0 TCPReceiveErrors=0 TCPSendErrors=0 UDPInErrors=0
May 22 15:16:04 unl-server-factory mita[1254]: 2022-05-22T15:16:04+08:00 INFO [metrics]
May 22 15:16:04 unl-server-factory mita[1254]: 2022-05-22T15:16:04+08:00 INFO [metrics - connections] ActiveOpens=0 CurrEstablished=0 MaxConn=3 PassiveOpens=9
May 22 15:16:04 unl-server-factory mita[1254]: 2022-05-22T15:16:04+08:00 INFO [metrics - server decryption] ServerDirectDecrypt=27 ServerFailedDirectDecrypt=0
May 22 15:16:04 unl-server-factory mita[1254]: 2022-05-22T15:16:04+08:00 INFO [metrics - client decryption] ClientDirectDecrypt=0 ClientFailedDirectDecrypt=0
May 22 15:16:04 unl-server-factory mita[1254]: 2022-05-22T15:16:04+08:00 INFO [metrics - UDP packets] InPkts=0 OutPkts=0
May 22 15:16:04 unl-server-factory mita[1254]: 2022-05-22T15:16:04+08:00 INFO [metrics - KCP segments] EarlyRetransSegs=0 FastRetransSegs=0 InSegs=0 LostSegs=0 OutOfWindowSegs=0 OutSegs=0 RepeatSegs=0 RetransSegs=0
May 22 15:16:04 unl-server-factory mita[1254]: 2022-05-22T15:16:04+08:00 INFO [metrics - UDP bytes] InBytes=0 OutBytes=0
May 22 15:16:04 unl-server-factory mita[1254]: 2022-05-22T15:16:04+08:00 INFO [metrics - KCP bytes] BytesReceived=0 BytesSent=0 PaddingSent=0
May 22 15:16:04 unl-server-factory mita[1254]: 2022-05-22T15:16:04+08:00 INFO [metrics - TCP bytes] InBytes=2090 OutBytes=1738 PaddingSent=838
May 22 15:16:04 unl-server-factory mita[1254]: 2022-05-22T15:16:04+08:00 INFO [metrics - replay protection] ReplayKnownSession=0 ReplayNewSession=0
May 22 15:16:04 unl-server-factory mita[1254]: 2022-05-22T15:16:04+08:00 INFO [metrics - error] KCPInErrors=0 KCPReceiveErrors=0 KCPSendErrors=0 TCPReceiveErrors=0 TCPSendErrors=0 UDPInErrors=0
May 22 15:17:04 unl-server-factory mita[1254]: 2022-05-22T15:17:04+08:00 INFO [metrics]
May 22 15:17:04 unl-server-factory mita[1254]: 2022-05-22T15:17:04+08:00 INFO [metrics - connections] ActiveOpens=0 CurrEstablished=0 MaxConn=3 PassiveOpens=9
May 22 15:17:04 unl-server-factory mita[1254]: 2022-05-22T15:17:04+08:00 INFO [metrics - server decryption] ServerDirectDecrypt=27 ServerFailedDirectDecrypt=0
May 22 15:17:04 unl-server-factory mita[1254]: 2022-05-22T15:17:04+08:00 INFO [metrics - client decryption] ClientDirectDecrypt=0 ClientFailedDirectDecrypt=0
May 22 15:17:04 unl-server-factory mita[1254]: 2022-05-22T15:17:04+08:00 INFO [metrics - UDP packets] InPkts=0 OutPkts=0
May 22 15:17:04 unl-server-factory mita[1254]: 2022-05-22T15:17:04+08:00 INFO [metrics - KCP segments] EarlyRetransSegs=0 FastRetransSegs=0 InSegs=0 LostSegs=0 OutOfWindowSegs=0 OutSegs=0 RepeatSegs=0 RetransSegs=0
May 22 15:17:04 unl-server-factory mita[1254]: 2022-05-22T15:17:04+08:00 INFO [metrics - UDP bytes] InBytes=0 OutBytes=0
May 22 15:17:04 unl-server-factory mita[1254]: 2022-05-22T15:17:04+08:00 INFO [metrics - KCP bytes] BytesReceived=0 BytesSent=0 PaddingSent=0
May 22 15:17:04 unl-server-factory mita[1254]: 2022-05-22T15:17:04+08:00 INFO [metrics - TCP bytes] InBytes=2090 OutBytes=1738 PaddingSent=838
May 22 15:17:04 unl-server-factory mita[1254]: 2022-05-22T15:17:04+08:00 INFO [metrics - replay protection] ReplayKnownSession=0 ReplayNewSession=0
May 22 15:17:04 unl-server-factory mita[1254]: 2022-05-22T15:17:04+08:00 INFO [metrics - error] KCPInErrors=0 KCPReceiveErrors=0 KCPSendErrors=0 TCPReceiveErro

**Comment by youjiajia-wc** [comment]
不能连接的现象是，无法打开任何网站，google之类的报错500，baidu之类的花了太长时间进行响应

**Comment by youjiajia-wc** [comment]
{
    "portBindings": [
        {
            "port": 10000,
            "protocol": "TCP"
        }
    ],
    "users": [
        {
            "name": "a",
            "password": "123"
        }
    ],
    "loggingLevel": "INFO"
}
以上是服务器配置，地址是2a07:e040:2:145::1，麻烦你试一下

**Comment by enfein** [comment]
简单来说，你的 VPS 有问题，请尽快更换 VPS 提供商。

我使用油管测试了一下，有时候，客户端发出指令后，服务器端完全没有响应。即便有响应，也会返回错误。下面是详细解释：

我更改了源代码来打印更多的日志信息。客户端的日志如下所示。

```
TRACE socks5 server accepted connection [127.0.0.1:1080 - 127.0.0.1:46324]
TRACE socks5 server starts to serve connection [127.0.0.1:1080 - 127.0.0.1:46324]
DEBUG creating new client TCP session [[xxxx]]:56930 - [xxxx]:10000]
TRACE TCPSession received request to read maximum 32768 bytes
TRACE TCPSession received request to write 3 bytes: [5 1 0]
TRACE TCPSession wrote 57 bytes to the network
TRACE TCPSession received 2 bytes actual payload: [5 0]
TRACE TCPSession received request to read maximum 32768 bytes
TRACE TCPSession received request to write 22 bytes: [5 1 0 3 15 119 119 119 46 121 111 117 116 117 98 101 46 99 111 109 1 187]
TRACE TCPSession wrote 71 bytes to the network
TRACE TCPSession received 10 bytes actual payload: [5 3 0 1 0 0 0 0 0 0]
TRACE TCPSession received request to read maximum 32768 bytes
DEBUG closing TCP session [[xxxx]:56930 - [xxxx]:10000]
```

请注意这里面服务器返回的信息

```
[5 3 0 1 0 0 0 0 0 0]
```

根据 socks5 协议 RFC 1928 的规定，第二个字节返回 `0x03` 代表 Network unreachable，也就是说服务器根本连不上 `www.youtube.com:443` 这个地址。

**Comment by youjiajia-wc** [comment]
> 简单来说，你的 VPS 有问题，请尽快更换 VPS 提供商。
> 
> 我使用油管测试了一下，有时候，客户端发出指令后，服务器端完全没有响应。即便有响应，也会返回错误。下面是详细解释：
> 
> 我更改了源代码来打印更多的日志信息。客户端的日志如下所示。
> 
> ```
> TRACE socks5 server accepted connection [127.0.0.1:1080 - 127.0.0.1:46324]
> TRACE socks5 server starts to serve connection [127.0.0.1:1080 - 127.0.0.1:46324]
> DEBUG creating new client TCP session [[xxxx]]:56930 - [xxxx]:10000]
> TRACE TCPSession received request to read maximum 32768 bytes
> TRACE TCPSession received request to write 3 bytes: [5 1 0]
> TRACE TCPSession wrote 57 bytes to the network
> TRACE TCPSession received 2 bytes actual payload: [5 0]
> TRACE TCPSession received request to read maximum 32768 bytes
> TRACE TCPSession received request to write 22 bytes: [5 1 0 3 15 119 119 119 46 121 111 117 116 117 98 101 46 99 111 109 1 187]
> TRACE TCPSession wrote 71 bytes to the network
> TRACE TCPSession received 10 bytes actual payload: [5 3 0 1 0 0 0 0 0 0]
> TRACE TCPSession received request to read maximum 32768 bytes
> DEBUG closing TCP session [[xxxx]:56930 - [xxxx]:10000]
> ```
> 
> 请注意这里面服务器返回的信息
> 
> ```
> [5 3 0 1 0 0 0 0 0 0]
> ```
> 
> 根据 socks5 协议 RFC 1928 的规定，第二个字节返回 `0x03` 代表 Network unreachable，也就是说服务器根本连不上 `www.youtube.com:443` 这个地址。

服务器肯定是能访问youtube的，因为单ss代理可以。

我等等再用双栈服务器或ipv4再试试，
至于为什么纯ipv6不行，就不知道原因了。
