### ISSUE TITLE
關於mieru配置文件的疑問

### ISSUE THREAD

**Issue by yatounoneko** [enfein/mieru#90]
似乎mieru的2.0.0版本會自動補全沒有輸入的配置？
```
"httpProxyPort":  8080,
"httpProxyListenLAN":  false
```
我沒有在配置文件中輸入這一段，但使用`mieru describe config`查看配置文件發現會自動添加httpProxy配置。
配置中我只添加了Socks5代理, 這個配置必須使用嗎？
還是說開啓了socks5後一定會配置這個代理？雖然沒看到端口佔用...

另外想請教下是否有使用批量端口號的配置？例如使用`5000:6000`所有端口這種配置...
現在人手打端口號已經複製的超級長了XD🤦‍♂️
雖然我知道[#32](https://github.com/enfein/mieru/issues/32)上有說過暫不支持，但[#81](https://github.com/enfein/mieru/issues/81#issuecomment-1722070326)中有提及到使用大於10個端口以上有助於防止端口封鎖的問題。
所以還是想問問是否有計劃支持？

**Comment by enfein** [comment]
关于 HTTP 代理的配置，应该是之前某个时候加上的，因为 `mieru apply config` 只是在打补丁，而不是覆盖掉之前的设置，所以这个东西会一直留在那里。如果你有用过 Kubernetes 应该知道我说的是什么意思。目前的解决办法是，把配置文件删掉，然后重新 `mieru apply config`。

端口段的支持，提交一个新的 feature request 吧，我排一下优先级，在某个版本实现一下。mieru v2 需要做的功能还挺多。
