### ISSUE TITLE
Empty file downloaded when open http://randomthing.icanhazip.com/

### ISSUE THREAD

**Issue by freenet4ever** [enfein/mieru#91]
When I visit this URL using mieru and mita v2.0 on firefox windows:

http://randomthing.icanhazip.com/

an empty file is downloaded.

why?

**Comment by enfein** [comment]
The website is not reachable.

My client log

```
DEBUG send HTTP proxy request to socks5 server failed: Get "http://randomthing.icanhazip.com/": SOCKS5 connection is not successful
```

My server log

```
DEBUG socks5 server listener  ServeConn() failed: handleRequest() failed: failed to resolve destination "randomthing.icanhazip.com": lookup randomthing.icanhazip.com on xxx: no such host
```

**Comment by enfein** [comment]
I didn't see an empty file got downloaded. My firefox returned an empty page.

**Comment by freenet4ever** [comment]
Its is not downloading a file now. But 2 days ago firefox returned an empty page when not connecting to mieru and downloaded an empty page when connected to mieru in that URL.

**Comment by freenet4ever** [comment]
> I didn't see an empty file got downloaded. My firefox returned an empty page
It was downloadin an empty page 2 days ago.

why with mieru HTTP proxy it shows empty page and with mieru socks proxy no page is shown> is this a bug?

**Comment by enfein** [comment]
@freenet4ever What is this website? My VPS can't lookup its DNS and can't load the page. Whether showing an empty page, show nothing, or download an empty file doesn't matter. If the website is broken, mieru won't be able to help.
