### ISSUE TITLE
Compare Mieru to other protocols

### ISSUE THREAD

**Issue by APT-ZERO** [enfein/mieru#97]
Hello,
Can you please compare Mieru to other protocols?
Why should some one use mieru instead of VMESS / VLESS and other protocols?
Thank you in advance.

**Comment by enfein** [comment]
I know a few advantages of mieru over VMESS.

1. mieru uses authenticated encryption while VMESS is not. GFW is unable to fabricate any packet with authenticated encryption.
2. mieru support both TCP and UDP, and it can wrap TCP inside UDP and UDP inside TCP.
3. mieru support multiplexing, so GFW doesn't know the begin and end of each session, makes it useless to do traffic analysis.

VLESS is almost always used with TLS so it is quite different. I haven't used VLESS for a long time so I don't know if there is a way to avoid TLS in TLS detection today.

**Comment by enfein** [comment]
I am not familiar with XTLS protocol. mieru is not based on TLS.
