### ISSUE TITLE
Preview of NekoBoxForAndroid with mieru plugin

### ISSUE THREAD

**Issue by enfein** [enfein/mieru#99]
We are working with NekoBox community to support mieru. Before everything is merged to upstream, you can download the preview APK files from https://github.com/enfein/NekoBoxForAndroid/releases and https://github.com/enfein/NekoBoxPlugins/releases.

Because we used a different certificate to build those APK files, it can't coexist with the official NekoBoxForAndroid app.

**Comment by freenet4ever** [comment]
It works but i needed to enable an option called FakeDNS in settings. without this option DNS requests were not resolving.

**Comment by enfein** [comment]
mieru itself does remote DNS resolution, so you will never need to worry about DNS being blocked. However, when mieru is used as a SagerNet or NekoBox plugin, the Android app does DNS resolution first then pass the request to mieru. The exact settings needed in the Android app will depend on your network.

I mentioned the same in https://github.com/enfein/mieru/issues/56#issuecomment-1435808922

**Comment by enfein** [comment]
Due to limitations in UI and NekoBox database schema, not all the features are supported.
